### ISSUE TITLE
Internal error on vendoring

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#1018]
**Describe the bug**
Running `go mod vendor` gives an internal error.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.11.0-40-generic x86_64

**Steps to Reproduce**

1. Run `go mod vendor` or `make dep`
2. See error

**Actual behavior**
```
$ go mod vendor
internal error: failed to find embedded files of golang.zx2c4.com/wireguard/rwcancel: //go:build comment without // +build comment
```

**Comment by jdknives** [comment]
@ersonp cant reproduce that on my machine. Am on the latest commit of develop and Linux.
