### ISSUE TITLE
prevent erroneous hypervisor configuration

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1046]
When the config is generated like this:

```
skywire-cli config gen --hypervisor-pks <visor-pk> -ro skywire-config.json
```

If the visor pk in question is the public key contained already in skywire-config.json then the above command should produce the same result as the following

```
skywire-cli config gen -iro skywire-config.json
```

That is, trying to set a visor to use it's own public key as hypervisor should generate the same configuration as intentionally generating the config with hypervisor enabled.

Currently this is not the behavior

need to default to producing a working config as much as possible. This is likely what someone intended to do if they did the first command.

This also represents an edge-case for auto configuration, when it might happen coincidentally or by happenstance. So it is preferable for this to be addressed.

**Comment by mrpalide** [comment]
If I understood correctly, you want to keep hypervisors PKs list during generate new config file from last config, right?
If the answer is yes, this is available by `-x` flag, so just use `skywire-cli config gen -irxo skywire-config.json`.
