### ISSUE TITLE
print public key from specified config file with skywire-cli

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1047]
The underlying issue, when using a script to automatically configure skywire, the script executes faster than the node starts.

So where I should be able to do `skywire-cli visor pk` and get the public key and print it out for the user, instead I have to manually parse the file like so:

```
  _pubkey=$(cat /opt/skywire/skywire.json | grep pk\")
  _pubkey=${_pubkey#*: }
  _pubkey=${_pubkey//,/}
  _pubkey=${_pubkey//\"/}
  #_pubkey=$(skywire-cli visor pk)
  echo "Visor Public Key:
${_pubkey}"

```

I propose that a command should be devised to print the public key from the specified config file.
something like this:

```
skywire-cli config read --file skywire-config.json pk
```

that is, read the public key from the specified config file.

This should be equivalent to
```
skywire-cli visor pk
```
except that it is not asking the running visor for this.

**Comment by mrpalide** [comment]
This feature is available with `-i` flag, so just use `skywire-cli visor pk -i skywire-config.json`.

**Comment by 0pcom** [comment]
That works, thanks!
