### ISSUE TITLE
skywire-cli and hypervisor api documentation

### ISSUE THREAD

**Issue by mrpalide** [skycoin/skywire#1051]
**Feature description**
We didn't use Hypervisor UI api more than itself, and just make same RPC endpoint to use in skywire-cli, also all flags instruction and usage of skywire-cli accessible just by `-h` flag, so for both we don't have any documentation. As talking with @0pcom these two docs will be useful at all, **hypervisor api/rpc** and **skywire-cli flags**.

**Comment by 0pcom** [comment]
thanks!

I might add to this that we could use some better documentation of the skywire config file itself, or a reference to what the fields are
