### ISSUE TITLE
`skywire-cli visor ip` subcommand

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1071]
you are using the vpn and you want to check from command line what your IP address is.

We should have this as a flag in skywire-cli.

```
skywire-cli visor ip --lan
```
this should return the LAN ip address of the running visor.

```
skywire-cli visor ip --inet 
```
this should return the public / internet ip address of the running visor.

We can query ip.skycoin.com for the internet / public ip address (?)

**Comment by jdknives** [comment]
@0pcom we already have the public IP in most cases from the NAT check. So should be simple enough to return it here via CLI.

**Comment by 0pcom** [comment]
added in #1475
