### ISSUE TITLE
Update visor by public key

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1080]
```
sjywire-cli visor update
```

should be able to take the public key of the visor or visors to update as argument

it is currently only possible via setting a different rpc address, assuming that address was public / accepting queries from LAN.

Do we want to use the rpc server in such a critical way for updates, and leave it so that anyone on the network could query the public key of a visor running at that ip address? By default the rpc server is now enabled in packages of skywire as of the 0.6.0-rc1 binary pre-release / testing release for compatability with the skybian setup in my pull request for skybian.

**Comment by jdknives** [comment]
RPC server should not be exposed publicly in the package. Issue is therefore obsolete. Was decided to make HTTP endpoint for obtaining the hypervisor pubkey.
