### ISSUE TITLE
windows vpn-client Writer:bufio.scanner token too long

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#1089]
**Describe the bug**
When trying to connect the vpn-client to the server an "Error while reading from Writer: bufio.Scanner: token too long" happens

**Environment information:**

vpn-client : windows (v0.6 rc2) windows installer
vpn-server: ubuntu-server (v0.5.1) from source

**Steps to Reproduce**
1. make persistent route from server to client
2. start vpn-server app
3. try to connect with vpn client

**Actual behavior**
vpn-client log:
[log (2).txt](https://github.com/skycoin/skywire/files/8025805/log.2.txt)

Is it normal in v0.5.1 that the dmsg server in the Broswer-UI shows 000000 ?
Maybe there is a problem.

**Expected behavior**
A working vpn connection

**Comment by mrpalide** [comment]
We checked logs, and that moment, DMSG server was down for a short time, so vpn connection was broken.
Also for vpn server, you have to be sure that your providers didn't disable tun/tap driver on your server. I have this problem with mines.
