### ISSUE TITLE
Create separate Systray UI package

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#1140]
**Feature description**

We currently maintain one Skywire deb package without the systray. Going forward, users should have the option to install the systray Skywire version from package. For that purpose we should have a `skywire-systray-bin` package that can be added on top of the base package to support the systray application.

**Comment by 0pcom** [comment]
will be done as soon as the separate-stray itself is implemented and a release binary exists for it
[#1317](https://github.com/skycoin/skywire/pull/1317)

**Comment by mrpalide** [comment]
We have multiple binary, actually two separate build, with and without systray. Also built binary with systray should run by `--systray` flag. So we can close this issue too.
