### ISSUE TITLE
Update the dmsghttp-config.json after successful connection to the dmsgd via dhmsgttp 

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#1142]
**Feature description**

Currently, the `dmsghttp-config.json` is static and needs to be updated by us every time there is any change in dmsg-servers. So to counter that we can have the visor update the `dmsghttp-config.json` or the dmsg-servers field in the config after it is successfully connected to the `dmsg-discovery` via dmsghttp. This will help with the `dmsghttp-config.json` being relatively up to date.

**Comment by jdknives** [comment]
Seems to be duplicate of #1105
