### ISSUE TITLE
Fix apps in config gen for windows

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#1172]
**Describe the bug**
Currently, the command `skywire-cli config gen` creates a config with all the apps. The only supported app on windows is `vpn-client` so the other apps are not needed in the config.

**Comment by mrpalide** [comment]
We had this before, by checking OS, but remove it and add new flag `--disableapps` that used in windows batch file too. So we should generate config on windows as bellow:
`skywire-cli config gen --disableapps skychat,skysocks,skysocks-client,vpn-server`
