### ISSUE TITLE
VPN-WebUI not updating correctly when connecting to a server

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#1198]
**Describe the bug**
When connecting to a vpn server in the vpn UI it first seem to not work (the 'connecting' spinner disappears), but the routes get added a few seconds later.Then the UI updates to being connected.

**Environment information:**

vpn-server: linux         v1.0.0-rc2
vpn-client: windows    v1.0.0-rc2

**Steps to Reproduce**
First Bug:
 1. Make transport
 2. connect to a server

**Actual behavior**
The "connecting" Box disappears after a few seconds and then the "ON"-button is shown again.
Only after the routes have been established a few seconds the "Connected" status appears again.

Also after a stopped vpn connection and pressing again the "ON"-button, first a "disconnected" Box appears.
And then the same behaviour: Box disappears, "ON"-Button shown, "Connected"-Box appears 

**Expected behavior**
The UI should stay at displaying "connecting" and not returning  to showing the "ON"-Button.

**Comment by ersonp** [comment]
Fixed in #1208 and #1204
