### ISSUE TITLE
VPN Client and Web-UI

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#1199]
**Describe the bug**
I had one case where the routes somehow got deleted while being connected to the vpn-server.
But the vpn-client didn't change its status.

**Environment information:**

vpn-server: linux         v1.0.0-rc2
vpn-client: windows    v1.0.0-rc2 (kill-switch on)

**Steps to Reproduce**

1. Connect to a vpn-server
-> I could not reproduce the bug until now, I guess it might be something with the kill-switch, but maybe something different.

What I tried:
I manually deleted the "Forward" Type Route inside my server while being connected and the vpn-client status does not change.
The "App" Type Route still is there.
When deleting the "App" Type Route the "Forward" Type Route also gets deleted and the vpn-client status changes to "disconnected".

But the bug appeared while no route was there on my server side. The client still showed "online"

**Actual behavior**
After the routes got deleted the vpn-client still was "green" and the vpn-ui still showed status "connected"

**Expected behavior**
the vpn-client should stop and behave accordingly to the situation of not having a route

My Powershell log said this, maybe this helps to understand what happended:

![2022-05-14 12_17_34-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/50741854/168423076-c13bf53e-85b6-4c5a-a751-cd1880c871af.png)

**Comment by mrpalide** [comment]
Cannot reproduce at current develop branch. (commit [036769f40d0c304d97ba22c462243391e230a826](https://github.com/skycoin/skywire/commit/036769f40d0c304d97ba22c462243391e230a826)). Maybe solved by recent VPN-Client status tasks done.
