### ISSUE TITLE
Remove transports from transport discovery

### ISSUE THREAD

**Issue by Kifen** [skycoin/skywire#120]
**Describe the bug**
Deleting a transport by `ID` is meant to delete a transport in `transport discovery`, but all it does is remove the transport locally. On restart of a visor, the transport are automatically re-established. 

**Environment information:**

- OS: Linux

**Steps to Reproduce**

1. Run an integration env
2. Add transport `skywire-cli node add-tp --pk [pubkey]`
3. Remove transport `skywire-cli node rm-tp [ID]`
4. Run `skywire-cli node ls-tp` to view transports

**Actual behavior**
The transports aren't removed 

**Expected behavior**
The transport should be removed locally and from `transport discovery`.

**Comment by jdknives** [comment]
Closed by above PR.
