### ISSUE TITLE
[M2] Multiple errors on visor restart

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire#122]
One may experience several different errors while trying to restart visor in the integration env. Error may be one of these:

1. `ERROR [transport]: Failed to register transports error="status: 500, error: ID already registered"`  always happens if running with stcp-startup
2.  if we run with `stcp-startup` after the error above apps are working. tried restarting visor B and then running `test-messaging-loop.sh`
3. if we run with `startup` apps stop working, all of the described errors appear in some random order, sometimes just some of them
4. if we runt `test-messaging-loop.sh` and then restart B, for `startup` the picture is the same, but for `stcp-startup` based on logs I may assume that packets are going through but no messages displayed on the console. strange thing

These need to be investigated and fixed one way or another

**Comment by jdknives** [comment]
These issues still appear as described above with `milestone2`.

**Comment by jdknives** [comment]
Fixed by now.
