### ISSUE TITLE
VPN UI not opening when the app is stopped

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#1220]
**Describe the bug**
Currently, the VPN UI only opens when the VPN client is running. This is happening due to the use of the API `/apps/vpn-client/connections` which gives the output
```
{
    "error": "no such app"
}
```
when the app is in a stopped state and it shows the app isn't available.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.13.0-44-generic x86_64

**Steps to Reproduce**

1. Start visor
2. Open VPN UI
3. See error

**Actual behavior**
![image](https://user-images.githubusercontent.com/38801159/170191909-fff99d39-546b-4b16-809f-87caec181bc8.png)

**Comment by Senyoret1** [comment]
Thanks for catching it. Solved in https://github.com/skycoin/skywire/pull/1225
