### ISSUE TITLE
Change VPN stats naming

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#1224]
**Describe the bug**
The Upload and download stats are converted into bit / second in the UI and the total Upload and download stats are in bytes. But both the values are denoted as `KB` and `MB`. We need to either specify the network stats as bits or Total stats as bytes or both so that it will be more clear.

The API provides the info in bytes.
```
[
    {
        "is_alive": true,
        "latency": 62,
        "upload_speed": 515,
        "download_speed": 248,
        "bandwidth_sent": 264200,
        "bandwidth_received": 317933,
        "error": "",
        "connection_duration": 128
    }
]
```
![image](https://user-images.githubusercontent.com/38801159/170248560-781e8f7f-5e95-4173-b471-2a330e7618dd.png)

**Comment by Senyoret1** [comment]
The lowercase b means bits and the uppercase b means bytes, just like ISPs tend to do. You can change it in the settings tab.
