### ISSUE TITLE
Implement audio call application

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#1255]
**Feature description**

@0pcom brought up, that it may be useful for testing, to implement some real-time communication application such as a voice chat. We need to investigate if there is a library out there that lets us implement a very basic call application over Skywire.

**Comment by NESS-Network** [comment]
enumer.org 
and built-in in NESS a Fiber coin

**Comment by NESS-Network** [comment]
![image](https://user-images.githubusercontent.com/74679402/173960421-13db5184-ac9d-4fa9-8a5d-7508d052ddfa.png)

**Comment by NESS-Network** [comment]
PBX services can be monetized, paid in coin hours for example

**Comment by 0pcom** [comment]
A working example / alternative which uses dmsgweb for streaming media which can be configured to use skywire routes

https://github.com/skycoin/skywire/wiki/dmsghttp+dmsgweb-streaming-media

It does not comprise a visor application at this time, however dmsgweb IS now included with the unified binary release.

closing this for now, on that note
