### ISSUE TITLE
Wrong latency/ping value on UI

### ISSUE THREAD

**Issue by mrpalide** [skycoin/skywire#1261]
**Describe the bug**
Sometimes we see wrong latency on UI, same as `4249871.2s` as ping value, but in logs we get a negative number like `-120`.
Seems time value on machine and server not synced and has a little difference, in milliseconds.

**Comment by jdknives** [comment]
The current fix just ignores a negative latency. This is not a clean solution. For the next release, we need to actually change the method we use for assessing the ping.
