### ISSUE TITLE
Create `skywire-cli vpn` command

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#1277]
**Feature description**

Working with the CLI for the VPN needs to be improved. Currently there are a range of features that we should provide: 

- get list of remote vpns with filters (by country for now, by connection metrics would be nice as well)
- connect to VPN server
- get status (returns info about VPN config and connection stats)

**Is your feature request related to a problem? Please describe.**
Using the VPN client on the CLI is not a very pleasant experience.

**Comment by 0pcom** [comment]
PR #1317
