### ISSUE TITLE
Updating mechanism for mainnet

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#129]
**Feature description**

We will need to implement an updating mechanism for `mainnet` before we switch over to `mainnet` from `testnet`

This is a ticket for discussing the best way to implemnt such a mechanism.

We need to ensure that:

- configuration files persist
- the update can be triggered from `hypervisor`
- the visor connects to hypervisor after update automatically

We need to update:

- [x] visor

- [x] skywire-cli

- [x] application binaries

**Comment by nkryuchkov** [comment]
@jdknives How do we need to update?
1. Clone the repository to a temporary folder, checkout to the required version, build and run.
2. Download binaries uploaded to GitHub releases, run.

**Comment by jdknives** [comment]
I think 2. sounds like the better way to go. We can tag releases every time we want to push a new version. For the other projects, we then have a Version file in the repo and additionally use version.skycoin.com, which returns the latest version for different binaries (currently only Skywallet firmware version and Skycoin Wallet version.) 

1. After we bumped the version.skycoin.net file with the latest Skywire version number, we could have Skywire check a specific version link from Github release page and download that.
2. Unzip it.
3. and run it.

We just need to make sure, we keep the config file and any other data that needs to persist. (Although I think the config file is the only relevant file at this point.) That would require us to have a version command (and hypervisor endpoint for returning version of visor).

**Comment by jdknives** [comment]
We may need to deal with updating scenarios, where new config values are required for visor to run. In that case we will need to update the config file before restart of the visor after an update. Also, we do not need the versioning for the application binaries and can just have them follow the versioning of the visor for now.

**Comment by nkryuchkov** [comment]
I created a separated issue for migrating configs: https://github.com/SkycoinProject/skywire-mainnet/issues/168.
