### ISSUE TITLE
`-p` flag on mac and windows

### ISSUE THREAD

**Issue by mrpalide** [skycoin/skywire#1293]
**Describe the bug**
Currently, `-p` flag on `skywire-cli` cannot determine path of config for Mac and Windows that use Installer package. We need fix this.
Also we need same as `skywire-autoconfig` on linux for windows and darwin too.

**Comment by 0pcom** [comment]
I will attempt to put the scripts and systemd services which are currently only in the skywire-scripts archive on a branch of the AUR repo that corresponds to the name of the package, so they can be more easily viewed.

I anticipate that this may complicate the builds slightly with the additional makedependency of `git`

certainly its more overhead, but it may be possible to actually use the same skywire-autoconfig script, with a few revisions, on macOS.
