### ISSUE TITLE
Windows .msi and MacOS package documentation

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1295]
Currently there is not good documentation for the windows .msi or macOS package

A few questions that should be answered by the documentation include but are not limited to:

1. What is the equivalent of the systemd service used for controlling the running process?
2. How do you manually start and  stop skywire via this framework?
3. How do you enable or disable skywire starting at boot?
4. What is the default config file path?
5. What is included in the packaging besides skywire? (i.e. scripts, services, batch files, etc.)
6. Where are the sources for the build of the installer or package?
7. What are the dependencies required to build either of these? .msi or mac package

**Comment by mrpalide** [comment]
windows:
1. no systemd service there. User just should run app from menu or desktop shortcut.
2. running that by shortcut on desktop or menu.
3. not available by UI or other things. Should add it manually by user to startup items.
4. `C:\Program Files\Skywire\skywire-config.json`
5. a `.bat` file that use for running skywire | a `new.update` file for checking update then regenerate config file for update version and etc.
6. `scripts\win_installer`
7. `wix` and `wintun` (both of them downloaded during building .msi installer)

**Comment by mrpalide** [comment]
mac:
1. no systemd service there. User just should run app from menu shortcut
2. starting by shortcut and stop by that too
3. not available in UI or other things. Should add manually by user to system preference
4. `/Users/{user}/Library/Application Support/Skywire/skywire-config.json`
5.  a bash script called `Skywire` that include a command to run skywire-visor on config. (Line 82 of create_installer.sh)
6. `scripts\mac_installer`
7. nothing
