### ISSUE TITLE
Allow to use hypervisor with dmsgpty

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#132]
**Feature description**

It would be desirable to be able to use dmsgpty with the PubKey of the hypervisor. This would allow a user to run the hypervisor and an instance of dmsgpty to remotely control their visors from within their management interface. We should also look into whether we can host the dmsgpty session in the manager interface. Apparently the testnet has been using https://xtermjs.org/ for that purpose.

**Comment by evanlinjin** [comment]
https://github.com/yudai/gotty

This project looks promising to use. It's backend is Golang as well.

**Comment by jdknives** [comment]
Dmsgpty, if used with visor, should be automatically whitelist the PubKey of the `hypervisor` registered in the visor config. 

Dmsgpty, if used with `hypervisor`, should use the keypair of the hypervisor for authentication.

**Comment by jdknives** [comment]
Closed by #166
