### ISSUE TITLE
`git clone` excessive bandwidth

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1340]
this repository when cloned is over 200mb,most of which is not the source code itself but objects in the history.

the sizeof the clone can be reduced without negative impact

**Comment by mrpalide** [comment]
Seems `makepkg` clone repo with `--depth` argument and get whole if history.

**Comment by mrpalide** [comment]
***A brief report on this issue***
`makepkg` used `--mirror` to fetch ALL (means EVERYTHING) on repo, I don't know why do this, but its suicide for our work. :)
```
if ! git clone ${GITFLAGS:---mirror} "$url" "$dir"; then
		error "$(gettext "Failure while downloading %s %s repo")" "${repo}" "git"
		plainerr "$(gettext "Aborting...")"
		exit 1
fi
```
available in `/usr/share/makepkg/source/git.sh` or [its repo](https://gitlab.archlinux.org/pacman/pacman/-/blob/master/scripts/libmakepkg/source/git.sh.in#L51)

Also I check blobs in `.pack` file, there is no binary file, and largest file was a `.go` script.

So we can do two thing for this issue:
1. Use my PR https://github.com/skycoin/AUR/pull/2, also I should add a condition that if folder be there then just pull it, not delete and clone again.
2. Modifying makepkg script itself and remove `--mirror` flag there.


@jdknives @0pcom What's your opinion guys?

**Comment by 0pcom** [comment]
@mrpalide i see now from your explaination that there is an upstream bug on this which is not going to be addressed

https://github.com/Jguer/yay/issues/972

https://bugs.archlinux.org/task/52957

i can probably download the .zip archive of whichever branch if it was an issue. once the initial mirror completes,only updates are fetched there and it allows any branch to be built easily.

I see that this was done intentionally to make the downloading of the git sources be done in one step.

@jdknives i cited this exact issue to you several years ago and you were able to reduce the size of the git clone --mirror at that time to a reasonable level.

that was what i hoped could happen again or might be done periodically.

**Comment by jdknives** [comment]
@0pcom @mrpalide fixed with a recent push. All forks and existing clones should be dropped and you guys should clone again.
