### ISSUE TITLE
HVUI Wrong service discovery endpoint for skysocks

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1397]
The service discovery endpoint for socks5 servers (skysocks-server) was changed some time ago, but this change was not reflected in the frontend sources

the current (incorrect) endpoint being queried is here:

https://sd.skycoin.com/api/services?type=proxy

which causes the list of skysocks proxy servers to never populate / indefinite loading as pictured below

![IMG_20221023_092807_412.jpg](https://user-images.githubusercontent.com/36607567/197397706-5b6b7450-cbae-4f6e-a2c2-b80f588c59e0.jpg)

the correct endpoint is here

https://sd.skycoin.com/api/services?type=skysocks

the fix should be applied here

https://github.com/skycoin/skywire/blob/7a0c6789306555162cdbb02cc90398a80d308dd7/static/skywire-manager-src/src/app/services/proxy-discovery.service.ts#L19

OR we should devise a way to avoid hardcoding this, which should avert similar errors in the future.

...

Also, a better error on null return from the service discovery should be reflected in the hypervisor UI. Perhaps even returning the endpoint which was queried; in such a way that a user may click a link to go to the service discovery endpoint for the specified service directly, which may be helpful for troubleshooting.

**Comment by Senyoret1** [comment]
The part about reacting correctly when the server returns `null` was added in https://github.com/skycoin/skywire/pull/1398 . The URL was not changed in the UI code because it was dicussed that changing the URL in the server would make it work in old versions automatically, without having to update.

**Comment by mrpalide** [comment]
Fixed here: https://github.com/SkycoinPro/skycoin-service-discovery/pull/119
