### ISSUE TITLE
Log filters are not respected by the API

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#1427]
**Describe the bug**
Calling the `GET /api/visors/{pk}/apps/skychat/logs?since=2022-12-14T12:00:00` does not return the log entries starting from 2022-12-14, it returns all the log entries, which could include data from years ago.

**Expected behavior**
It should return the log entries created on 2022-12-14T12:00:00 and later, all previous entries should be ignored. However, maybe we should define the exact format that should be used for sending the data with the `since` param.

**Comment by 0pcom** [comment]
solved in #1507
