### ISSUE TITLE
Api/nodes call hangs on hypervisor

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#143]
**Describe the bug**

Link to the issue description https://github.com/SkycoinProject/skywire-mainnet/issues/123#issuecomment-578439654

**Comment by nkryuchkov** [comment]
@Darkren I cannot reproduce it on the current milestone 2 branches. Could you please try to reproduce?

**Comment by evanlinjin** [comment]
@jdknives From my testing in branch [`evanlinjin:feature/m3-dmsgpty-hypervisor`](https://github.com/SkycoinProject/skywire-mainnet/pull/166), this bug no longer occurs. Even with multiple restarts of hypervisor.

**Comment by jdknives** [comment]
Tested on deployment and this is no issue anymore.
