### ISSUE TITLE
Skysocks cannot be restarted

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#144]
**Describe the bug**
Originally reported by @Darkren here: https://github.com/SkycoinProject/skywire-mainnet/issues/123

 Logs of visor hosting skysocks while changing password:

![](https://user-images.githubusercontent.com/13316082/73166306-ab6edc80-4106-11ea-9c10-32b7b2d75ce1.png)

Probably restart happened too soon after socket closed, cause when I tried to start if from hypervisor, skysocks sucessfully started. Not sure

**Comment by Darkren** [comment]
Actually passcode change goes ok sometimes. But sometimes the picture is as above. Looking deep

**Comment by jdknives** [comment]
Closed by #149
