### ISSUE TITLE
Cannot use proxy after restart

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#147]
Originally described by @Darkren here: https://github.com/SkycoinProject/skywire-mainnet/issues/123

I did the following:

1. Started visors A and C on local machine
2. Added transport C->B, A->B
3. Tried changing password and PK for skysocks
4. Tried curling through skysocks - it works
5. Requested visor restart from hypervisor for C where skysocks-client is hosted. It went down and rose back up just great. but then, logs:

![](https://user-images.githubusercontent.com/13316082/73167523-07d2fb80-4109-11ea-9e49-016771410bbf.png)
Then tried curling through proxy and got this:

![](https://user-images.githubusercontent.com/13316082/73167623-394bc700-4109-11ea-9b28-49f58d7c8e7d.png)

Restarting skysocks-client from hypervisor doesn't save the day, CURL request hangs after that

**Comment by Darkren** [comment]
Need to check but probably this happens right after the visor restart, no more actions needed. I'll check. Seems like we're refreshing transports from discovery on visor start, but we don't refersh routing table. It gets lost and router just can't handle incoming packets

**Comment by evanlinjin** [comment]
As discussed on Discord [(here)](https://discordapp.com/channels/466450852098605059/466450852098605061/674619201067024395), this bug may be a result of a faulty implementation of `router`.

We may need to ensure the `router` enforces the following behavior:
1. If we don't receive ping after timeout, close the route.
2. If we can't send pong, close the route.

Here is a link to the relevant specs: https://github.com/SkycoinPro/skywire-specs/blob/master/proposals/router2.md#routingrule-changes

**Comment by evanlinjin** [comment]
As a response to @Darkren 's message on Discord [(here)](https://discordapp.com/channels/466450852098605059/466450852098605061/675283458100297728), I recommend the following:
1. Initialize `routing.Table` within `router.Router`.
2. Add a new method to `routing.Table`: `(*routing.Table).CollectGarbage() []RouteDescriptor` which returns the route descriptors from all the `ConsumeRule`s and `ForwardRule`s that it has deleted.
3. The garbage collection logic will be repositioned to be called within `router.Router`. Every time `CollectGarbage()` is called, the returned route descriptors will be used to close the relevant route groups.

Thoughts?
