### ISSUE TITLE
Authenticated API  for setting recommended transports over dmsg

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1497]
Currently:
* Transports are automatically established to public visors when public_autoconnect is set to true
* Transports are automatically established for entries in the config file under persistent transports

We need an authenticated API for setting transports over dmsg for that visor.

We have similar functionality available to the user via the hypervisor UI and the cli.
```
skywire-cli tp add -t <transport-type> <public-key>
```

Think of this in terms of the hypervisor. When the visor connects to the hypervisor, it serves RPC to the hypervisor.

Instead of actively connecting to a public key, we wish to allow connections from certain whitelisted public keys over dmsg

We want to serve a subset of the rpc for setting transports to the connecting, whitelisted public key.

The authentication should use ECDH

More details will be added to this ticket

**Comment by jdknives** [comment]
@0pcom cloosing this as we already have a service and corresponding module for it. https://github.com/skycoin/skywire/pull/697
