### ISSUE TITLE
DMSG server is 0000000…

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#1504]
When  openning the Hypervisor UI just after startinmg the visor, at least sometimes, the DMSG server is 000000000000000000000000000000000000000000000000000000000000000000. When this happens, trying to open the DMSG terminal fails, and the visor console shows an error like this: runtime error: `invalid memory address or nil pointer dereference`

If due to the async nature of the procedure, the problem can not be fixed, we should define an appropriate msg to show in the UI instead of the 00000... address and block the ability to open the terminal until an appropriate address is returned by the back-end.

**Comment by 0pcom** [comment]
yes it is 000000000000000000000000000000000000000000000000000000000000000000 until the connection is made to the dmsg network

normally this connection happens faster, but recently there are a lot of dead entries in dmsg-discovery
