### ISSUE TITLE
Don't connect to uptime tracker when config field is blank

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1540]
When no uptime tracker is specified, the visor will still attempt to connect to it as if the service is running on localhost

connection should not be attempted if the service is not configured

**Comment by mrpalide** [comment]
We have this situation, just should remove entire part of service config, it means for UT, you should remove entire scope in config file. Means change it from 

![image](https://github.com/skycoin/skywire/assets/79150699/ff5297de-77de-4f11-a5e0-540faedbdd0f)
to

![image](https://github.com/skycoin/skywire/assets/79150699/e98965e3-4a3f-47cf-a17c-743185ed8a0e)

We have this situation for **uptime-tracker** and **dmsg-discovery**. Other services are related and should be there at all.
