### ISSUE TITLE
Merge milestone2

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#159]
Depends on #122 #143 #147 .

After the above issues have been fixed, we need to resolve the merge conflicts and merge `milestone2` into `master`. A new `dev` branch should be created afterwards. We need to test whether https://github.com/SkycoinPro/skywire-services/issues/21 still persists with m2.

**Comment by nkryuchkov** [comment]
- [ ] https://github.com/SkycoinProject/skywire-mainnet/pull/219

- [ ] https://github.com/SkycoinPro/skywire-services/pull/106

- [ ] https://github.com/SkycoinProject/dmsg/pull/80
