### ISSUE TITLE
Problem when recreating transports

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#160]
**Describe the bug**
If a transport is removed and then created again, the Hypervisor is no longer able to get information about the remote node.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**

1. Start some nodes using the `make integration-run-generic` command of the `skywire-services` repository (tested using the `milestone2` branch of the `skywire-mainnet` repo and the `mainnet-milestone2` branch of the  `skywire-services`  repo).
2. Create a transport form the 0348c... visor to the 024ec... visor by calling `POST /api/visors/0348c941c5015a05c455ff238af2e57fb8f914c399aab604e9abb5b32b91a4c1fe/transports` with `{"remote_pk":"024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7","transport_type":"dmsg","public":true}` as content.
3. Call `GET /api/visors/024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7/transports` and `GET /api/visors/0348c941c5015a05c455ff238af2e57fb8f914c399aab604e9abb5b32b91a4c1fe/transports` to check the new transport exists on both visors.
4. Call `DELETE /api/visors/0348c941c5015a05c455ff238af2e57fb8f914c399aab604e9abb5b32b91a4c1fe/transports/221ab9df-7cc7-0cca-9874-9cd72150865b` to remove the transport from the 0348c... visor.
5. Make the calls of step 3 again. You will see the transport is removed from the 0348c... visor, due to the call made on step 4. However, the transport will still be present in the 024ec... visor, which appears to be an error.
6. Repear the call from step 2, to create the transport again. This time the call will take much more time. In my case the first call is completed in just some ms, but the second one takes about 20 secs.
7. Make the calls of step 3 again. You will see the transport on the 0348c... visor, but the request for the 024ec... will never be completed.
8. Call `GET /api/visors` to get the info about all the visors. The call will never return a response.

**Actual behavior**
After removing the transport from the 0348c... visor it will not be removed from the 024ec... visor. Also, after recreating the transport some API endpoints will stop responding.

**Expected behavior**
The transport should be removed from both visors and after recreating the transport the API should continue to work well.

**Additional context**
Not sure, but may be related to https://github.com/SkycoinProject/skywire-mainnet/issues/143 and https://github.com/SkycoinProject/skywire-mainnet/issues/30

**Possible implementation**

**Comment by evanlinjin** [comment]
Seems to be related to  #171 
Also getting log messages:
```
[2020-02-28T17:13:06+08:00] WARN [tp_manager]: underlying 'write' tp failed, will retry: settlement handshake failed: context deadline exceeded
[2020-02-28T17:13:06+08:00] ERROR [transport]: Failed to update statuses error="Post http://localhost:9091/statuses: context deadline exceeded"
```
