### ISSUE TITLE
Intermittent issue connecting to services over dmsghttp

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1603]
unfortunately this is very hard to reproduce consistently and comprises several issues

* dmsg servers in the dmsghttp-config.json cannot be connected to (randomly) at times or the connection breaks

* for me, transport discovery and dmsg discovery couldn't be connected to over dmsghttp until I edited the file to remove all but mohammed's dmsg server

* we need the dmsg key : port included with the services on the /health endpoint so we can independently check the key of the running service

* we need a mechanism for updating the dmsghttp-config (just a simple fetch of the file from develop or add to the conf service and fetch from there) for those times when we update the file ; to avoid needing to make a new release in those instances.

* we should consider having the dmsghttp-config able to be fetched from the conf service itself

* we should have a way for the dmsghttp-config fetched from conf.skywire.skycoin.com/dmsghttp to be updated or fetch the current keys from the running services intermittently ; hourly or daily

* we need better integration tests for visors running dmsghttp-config to catch errors related to the dmsghttp-config or connecting to services over dmsghttp

**Comment by 0pcom** [comment]
The issue is largely related to the deployment.

I can verify that I have no errors in connecting to any service using the dmsghttp-config at this time.

An update of the dmsghttp-config can be done very simply in the package autoconfig script, and I can implement that on the next package release.

**Comment by jdknives** [comment]
Fixed by #15 and #1628.
