### ISSUE TITLE
Verify transport status

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1607]
A while back I noticed, looking at the transport discovery there was a transport to a visor I was running which did not exist for my visor and could not be created.

The map of transports has not changed in some time and most of the transports there are not generating any bandwidth logging. They may be old visor versions which do not generate this logging.

## TESTING

* Refer to the map of transports here
 https://fiber.magnetosphere.net/transports-map
 
* create a transport to one of the keys in TPD which has other transports.
 
* connect to a service like the proxy server which is running on a key which the visor you connected to has a transport to
 
 OR
 
* Ping the visor that you do not have a transport to directly but for which there should be a valid route to
 
* Record the result and update this ticket

**Comment by 0pcom** [comment]
I've checked that all the keys with transports are actually online ; they are
```
skywire-cli ut -o | while read _online ; do _HASTP="0" cat withtps.txt | while read _withtp ; do if [[ "$_online" == "$_withtp" ]] ; then _HASTP="1" ; fi ; done ; if [[ "$_HASTP" == "0" ]] ; then echo "$_online" ; fi ; done
```

the list of keys with transports can be obtained from the address resolver.
http://ar.skywire.skycoin.com/transports

it seems the only good way to verify the transport status is to attempt to ping the visor through a transport as outlined in original issue comment.

**Comment by mrpalide** [comment]
This issue solved due to running tpd-monitor.
