### ISSUE TITLE
Include service configuration in the survey & determine required / supported configuration for rewards

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1612]
The deployment services which are configured in the visor should be included in the survey.

Currently it is possible to have a misconfiguration of production deployment services for the visor or to have a local deployment configuration where the local services such as transport discovery, address resolver, etc. are set but using the uptime tracker from prod

If the local services use the dmsg-discovery for prod then it would be more or less a valid config; however, any deviation from the prod config calls into question what the required config fields should be, and what deviation is allowed currently that will still be rewarded

OR

we need to determine what services must match with conf.skywire.skycoin.com

## Essential Configuration
To my knowledge, the following services are essential to match conf.skywire.skycoin.com
* Survey whitelist
* route setup-nodes
* transport sertup-nodes
* dmsg discovery
* uptime tracker

The other services may or may not be necessary to match those in prod - **to be determined**

## Questions:

* Which services are basically a whitelist (allowed to act on the visor)
* Which services are used by the visor in such a way that the visor can use a different or locally running service without affecting its ability to have transports established to it or to make a route which includes that visor
* Which services are both a whitelist and used by the visor ; in other words, the service configured is permitted to act on the visor as well as being consumed by the visor, depending on the circumstance.

## Dmsg-discovery

Any locally running service currently should use the dmsg-discovery on prod, (until we allow for multiple dmsg-discovery servers to be configured)

Similarly, the visor needs to use the same dmsg-discovery as all the services it has configured use - until we add support for multiple services of the same type to be configured.

## Route setup-node

The only service which is both whitelisted and used by the visor, that I know of, are the route setup-nodes

At least one (working) route setup-node must be the same for every visor seeking rewards in the skywire network for routes to be able to be established.

The route setup-node is whitelisted by the visor to be able to make a route which includes that visor

The route setup-node is also dialed or connected to by the visor in order to return a route that can be used by the visor

## Transport discovery

If the visor has a different transport discovery listed, then the visor will only register or de-register transports with the transport-discovery it has configured.

The address resolver, being a field within the transport service configuration struct, must use the same transport and dmsg discovery. So AR and TPD are essentially a set of services which must be deployed and configured together

**Can transport discovery and address resolver from a different deployment be substituted for those running on prod, assuming those services which belong to a different deployment are using the same dmsg-discovery?**

## Service Discovery

The service discovery would seem to be non-critical to be in the same deployment, as long as the same dmsg-discovery was used. But even that may not be required if the service is only connected to over http and not dmsghttp

Of course this means that the services which are run by the visor would never be advertised in the service discovery on prod, but they should actually still be accessible; just hidden

**Comment by mrpalide** [comment]
Fixed here: https://github.com/skycoin/skywire/pull/1721
