### ISSUE TITLE
Can't start a visor again after using the restart API endpoint

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#164]
**Describe the bug**
If a visor is restarted by using the `GET /api/visors/{visor}/restart` API endpoint, it will not be possible to start it again after completelly stopping it, until restarting the computer.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**

1. Start some visors using the `make integration-run-generic` command of the `skywire-services` repository (tested using the `milestone2` branch of the `skywire-mainnet` repo and the `mainnet-milestone2` branch of the  `skywire-services`  repo).
2. Call `GET /api/visors/024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7/restart` to restart VisorA. The command window for VisorA will show the restarting procedure being executed.
3. Stop the test enviroment of the `skywire-mainnet` repo by running `make integration-teardown; tmux kill-server`.
4. Start the test enviroment again by running the `make integration-run-generic` command. The VisorA window will show that it was not possible to start the Visor. The error msg is `Failed to initialize visor: failed to init network: failed to initiate 'stcp': listen tcp 127.0.0.1:9496: bind: address already in use`.

**Actual behavior**
After restarting the visor, it is not possible to start it again if at some point it is stopped. Trying to stop and start the test enviroment several times does not solve the problem. The visor can be started again only after restarting the computer.

**Expected behavior**
The Visor should start normally.

**Additional context**
Not sure if the problem is due to something on this repo or the  `skywire-services`  repo.

**Possible implementation**

**Comment by nkryuchkov** [comment]
https://github.com/SkycoinPro/skywire-services/pull/84 fixes this.
