### ISSUE TITLE
Invalid PubKey

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#167]
**Describe the bug**

When running visor in test deployment, it returns:

`FATAL [skywire]: Failed to initialize visor: invalid transport discovery config: httpauth: error getting current nonce: status: 400 <- In
valid public key`

When running a visor outside of test-deployment, this error is not encountered.

**Comment by nkryuchkov** [comment]
There was an issue with the `skywire-visor` config on test deployment. Fixed.
