### ISSUE TITLE
Config migration on binaries update

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#168]
**Feature description**

> We may need to deal with updating scenarios, where new config values are required for visor to run. In that case we will need to update the config file before restart of the visor after an update.

_Originally posted by @jdknives in https://github.com/SkycoinProject/skywire-mainnet/issues/129#issuecomment-588314046_

https://github.com/SkycoinProject/skywire-mainnet/pull/153 implements support for updating `skywire-visor`, `skywire-cli` and app binaries. However, the scenario with new config values was not implemented.

**Comment by jdknives** [comment]
Fixed by #246 246
