### ISSUE TITLE
Improve visor configuration experience

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#173]
**Issues**
- A feature for reducing the likelihood of having misspelled/wrong config values. [(link)](https://github.com/SkycoinProject/skywire-mainnet/issues/173#issuecomment-594441598)
- Add points to config methods to avoid golang default values. [(link)](https://github.com/SkycoinProject/skywire-mainnet/issues/173#issuecomment-594450919)
- Generate config READMEs/help. [(link)](https://github.com/SkycoinProject/skywire-mainnet/issues/173#issuecomment-595135072)
- We should have a standard for configuration of execs. [(link)](https://github.com/SkycoinProject/skywire-mainnet/issues/173#issuecomment-595141495)

**Comment by jdknives** [comment]
A feature for reducing the likelihood of having misspelled/wrong config values (maybe proper warnings in logs) would be required. We had two cases already: 

- misspelled config value for `setup node` 
- wrong term used for config value of `dmsg.Server`

**Comment by nkryuchkov** [comment]
Go default values sometimes are annoying for configs. Maybe we should add pointers to types in configs to have `nil`s or panics instead of `0`/`false`/`""`s where keys are not specified.

**Comment by evanlinjin** [comment]
We should switch over to something like [JSON 5](https://spec.json5.org/) to make use of commenting on config generation. There is already a [official golang library](https://github.com/json5/json5-go). Although it seems to not be updated for a while...

**Comment by evanlinjin** [comment]
We need an easy way to generate config READMEs and commandline help from code. This way we don't need to update multiple different files with every change. [(Discord)](https://discordapp.com/channels/466450852098605059/684712974723973134/685050985474686987)

**Comment by evanlinjin** [comment]
We should have a standard for configuration of execs. This is currently still in discussion.

As suggested by @evanlinjin on [Discord](https://discordapp.com/channels/466450852098605059/684712974723973134/685058508105711623):
1. Args for execs: debug level, where to source config.
3. Config file: Everything else.
4. Create a `gen-config` sub-cmd on all execs that generates default config.

As suggested by @nkryuchkov on [Discord](https://discordapp.com/channels/466450852098605059/684712974723973134/685062481046929410):
Personally, I like the way parity uses: CLI and config are interchangeable; no envs; if no config/CLI found, it is generated

Related resources:
- Parity: https://wiki.parity.io/Configuring-Parity-Ethereum
