### ISSUE TITLE
Rename `Loop` to `RouteGroup` for hypervisor endpoints and RPC.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#180]
## TODO
- [ ] Rename `Loop` to `RouteGroup` for hypervisor endpoints and RPC.

_Originally posted by @evanlinjin in https://github.com/SkycoinProject/skywire-mainnet/pull/166#issuecomment-593882773_

**Comment by Kifen** [comment]
@evanlinjin how about the function in hypervisor `getLoop`, should it be renamed to `getRouteGroup`? Also should the function `Loops` in `RPCClient` interface be renamed to `RouteGroups` ?

**Comment by jdknives** [comment]
I think that would make sense.
