### ISSUE TITLE
add `gocyclo` to CI checks

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1865]
The [go report card for skywire](https://goreportcard.com/report/github.com/skycoin/skywire) shows 100% in every category except `gocyclo`

It would be worthwhile to include the results of the `gocyclo` checks in the CI pipeline ; with additional makefile directive which corresponds to it's use.

The current `gocyclo` results are as follows:

## gocyclo 96%

[Gocyclo](https://github.com/fzipp/gocyclo) calculates cyclomatic complexities of functions in Go source code. The cyclomatic complexity of a function is calculated according to the following rules: 1 is the base complexity of a function +1 for each 'if', 'for', 'case', '&&' or '||' Go Report Card warns on functions with cyclomatic complexity > 15.

[cmd/skywire-cli/commands/visor/top.go](https://github.com/skycoin/skywire/blob/v1.3.25/cmd/skywire-cli/commands/visor/top.go)
[Line 229](https://github.com/skycoin/skywire/blob/v1.3.25/cmd/skywire-cli/commands/visor/top.go#L229): warning: cyclomatic complexity 64 of function eventLoop() is high (> 15) (gocyclo)
[Line 94](https://github.com/skycoin/skywire/blob/v1.3.25/cmd/skywire-cli/commands/visor/top.go#L94): warning: cyclomatic complexity 23 of function parseArgs() is high (> 15) (gocyclo)
[Line 411](https://github.com/skycoin/skywire/blob/v1.3.25/cmd/skywire-cli/commands/visor/top.go#L411): warning: cyclomatic complexity 16 of function run() is high (> 15) (gocyclo)
[pkg/visor/hypervisor.go](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/hypervisor.go)
[Line 624](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/hypervisor.go#L624): warning: cyclomatic complexity 38 of function (*Hypervisor).putApp() is high (> 15) (gocyclo)
[pkg/visor/init.go](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/init.go)
[Line 890](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/init.go#L890): warning: cyclomatic complexity 17 of function getRouteSetupHooks() is high (> 15) (gocyclo)
[Line 1411](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/init.go#L1411): warning: cyclomatic complexity 16 of function initDmsgpty() is high (> 15) (gocyclo)
[cmd/skywire-cli/commands/rewards/ui.go](https://github.com/skycoin/skywire/blob/v1.3.25/cmd/skywire-cli/commands/rewards/ui.go)
[Line 241](https://github.com/skycoin/skywire/blob/v1.3.25/cmd/skywire-cli/commands/rewards/ui.go#L241): warning: cyclomatic complexity 114 of function server() is high (> 15) (gocyclo)
[cmd/skywire-cli/commands/log/st.go](https://github.com/skycoin/skywire/blob/v1.3.25/cmd/skywire-cli/commands/log/st.go)
[Line 48](https://github.com/skycoin/skywire/blob/v1.3.25/cmd/skywire-cli/commands/log/st.go#L48): warning: cyclomatic complexity 42 of function makeTree() is high (> 15) (gocyclo)
[pkg/visor/visorconfig/config.go](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/visorconfig/config.go)
[Line 143](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/visorconfig/config.go#L143): warning: cyclomatic complexity 20 of function MakeDefaultConfig() is high (> 15) (gocyclo)
[internal/vpn/client.go](https://github.com/skycoin/skywire/blob/v1.3.25/internal/vpn/client.go)
[Line 345](https://github.com/skycoin/skywire/blob/v1.3.25/internal/vpn/client.go#L345): warning: cyclomatic complexity 19 of function (*Client).serveConn() is high (> 15) (gocyclo)
[pkg/visor/cmd.go](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/cmd.go)
[Line 60](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/visor/cmd.go#L60): warning: cyclomatic complexity 19 of function init() is high (> 15) (gocyclo)
[pkg/router/router.go](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/router/router.go)
[Line 487](https://github.com/skycoin/skywire/blob/v1.3.25/pkg/router/router.go#L487): warning: cyclomatic complexity 16 of function (*router).saveRouteGroupRules() is high (> 15) (gocyclo)

## Actionability

the results of the `gocyclo` test indicates areas where the code may be improved to reduce overall cyclomatic complexities of functions. They should not be considered breaking errors, but the results of these tests should be more visible in the CI pipeline so that they may be addressed in the future.

**Comment by mrpalide** [comment]
Partially fixed in #1904, and new ticket created at #1905.
