### ISSUE TITLE
Deployment issue causing incorrect ip address in survey

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1866]
issue regarding the new mechanism for getting the ip address from the dmsg server - it's related to the deployment.

It appears that the reward calculation numbers are incorrect because the ip addresses in the surveys are incorrect.

Many visors are getting the same ip address in the survey as others - when they actually don't have the same ip address.
```
$ jq '.ip_address' log_collecting/*/node-info.json | grep "170.187.228.178" | wc -l
114
```

114 visors at the same ip address here

That is why the numbers for rewards look so wrong ; it's hitting the ip limit because at least some of the dmsg servers in our deployment are returning the wrong ip address. Probably some internal ip address of linode or traefik.

@mrpalide if you could look at this in the deployment ASAP that would be sincerely appreciated.

**Comment by mrpalide** [comment]
Now fixed after migration complete from k8s cluster to bare metal server.
