### ISSUE TITLE
sudph transports not working - `ERROR [sudph]: Failed to listen on port: handshake failed: timeout`

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1867]
After the deployment outage at the end of June, it seems that sudpn transports do not work because the visor cannot reach the address resolver over UDP.

```
ERROR [sudph]: Failed to listen on port: handshake failed: timeout
```

In the past, this error has been due to some mis-configuration or overlooked port forwarding for the address resolver.

**Comment by jdknives** [comment]
Fixed.
