### ISSUE TITLE
Tests use dependencies from go/pkg/mod instead of vendor

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#204]
**Describe the bug**
Tests do not test if `vendor` contains the correct code. As `vendor` is used for building binaries, we also need to use it for tests.

The issue may also be related to other repositories.

**Steps to Reproduce**
1. Add a `panic()` statement in any code in `vendor` used by tests.
2. Run `make check`.

**Possible implementation**
A `-mod=vendor` flag passed to tests may lead to the desired behavior. However, this needs to be checked.

**Comment by jdknives** [comment]
Cannot be reproduced.

**Comment by jdknives** [comment]
Closed by #329
