### ISSUE TITLE
Create an executable for generating README and command line help from config structs.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#205]
We need an easy way to generate config READMEs and commandline help from code. This way we don't need to update multiple different files with every change. [(Discord)](https://discordapp.com/channels/466450852098605059/684712974723973134/685050985474686987)

_Originally posted by @evanlinjin in https://github.com/SkycoinProject/skywire-mainnet/issues/173#issuecomment-595135072_

**Comment by jdknives** [comment]
Closed by the various PRs from @Darkren
