### ISSUE TITLE
Can not update a visor after the first try

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#209]
**Describe the bug**
When calling the `POST /visors/{pk}/update` API endpoint for the first time it responds corretly, but calling the endpoint again always result in errors, until the visor is restarted.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**

1. Start some nodes using the `make integration-run-generic` command of the `skywire-services` repository (tested using the `milestone2` branch of the `skywire-mainnet` repo and the `mainnet-milestone2` branch of the  `skywire-services`  repo).
2. Call `POST /api/visors/024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7/update` to update VisorA. The API should return `true` and the VisorA console should show this:
![m1](https://user-images.githubusercontent.com/34079003/76095626-fcda7900-5f9a-11ea-99dd-13c175aa1346.png)
2. Call `POST /api/visors/024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7/update` again to update VisorA. This time the API returns `{ "error": "updating already started" }` and the VisorA console shows this:
![m2](https://user-images.githubusercontent.com/34079003/76095639-02d05a00-5f9b-11ea-8a71-cb8d48a33b20.png)

**Actual behavior**
After the first attempt to update VisorA, all calls to for trying to update the visor fail.

**Expected behavior**
The calls should work corretly.

**Additional context**

**Possible implementation**

**Comment by jdknives** [comment]
Fixed by the new release. Due to the release 0.1.3 being outdated, the visor would not automatically reconnect to visor after restart.
