### ISSUE TITLE
Simplify build process for Manager UI

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#224]
**Feature description**

Simplify the build process for the manager. Eventually we should be able to build hypervisor and manager UI with one command similar to the way it works in the [testnet](https://github.com/SkycoinProject/skywire#run-skywire-manager). 

**Related Problem**

Currently, we need to go through this [process](https://github.com/SkycoinProject/skywire-mainnet/tree/master/static/skywire-manager-src#prerequisites) to setup the manager UI. Thats too much work for many people imo.

**Comment by Darkren** [comment]
@jdknives as a simplest solution I may just add a script which:
1. Builds hypervisor
2. Install NPM packages
3. Runs command to generate certs
4. Runs hypervisor with `nohup`
5. Runs manager ui

Would that be enough for the meantime, or should I come up with something else? Cause looking at the testnet I see that it's just totally different. And it's rather confusing

**Comment by jdknives** [comment]
Fixed by #236
