### ISSUE TITLE
Investigate Visor Panic upon Shutdown

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#225]
**Describe the bug**
The build process was not successful and apps were not built properly on `master` branch. After running `visor`, I sent a `Ctrl+C` and the following panic popped up. 

[logs.txt](https://github.com/SkycoinProject/skywire-mainnet/files/4318221/logs.txt)

@Darkren suggested we should look into this. 

**Environment information:**

- OS: MacOS

**Steps to Reproduce**
1. Build visor without building apps on `master`.
2. Run `skywire-visor`. 
3. `Ctrl+C`

**Comment by evanlinjin** [comment]
@jdknives I'm pretty sure this does not happen anymore... Maybe we can reopen this issue once we get the relevant logs?
