### ISSUE TITLE
Packaging should put skywire apps in a separate directory.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#227]
**Feature description**

Currently, release packages put all binaries in the same level. However, apps should really be separated into a nested directory.

**Is your feature request related to a problem? Please describe.**
This makes it easier to get things up and running.

**Describe the solution you'd like**
Current layout:
```
.
├── CHANGELOG.md
├── README.md
├── skychat
├── skysocks
├── skysocks-client
├── skywire-cli
└── skywire-visor
```
Proposed layout:
```
.
├── apps
│   ├── skychat
│   ├── skysocks
│   └── skysocks-client
├── CHANGELOG.md
├── README.md
├── skywire-cli
└── skywire-visor

```

**Comment by jdknives** [comment]
Closed by #228
