### ISSUE TITLE
Proxy won't work in the integration env

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire#233]
**Describe the bug**
When you try `curl`ing in the integration proxy env, request won't succeed

**Environment information:**
Independent

**Steps to Reproduce**

1. Go to services
2. `make dep` to update deps
3. `make integration-build`
4. `make integration-run-proxy`
5. `./integration/dmsg-startup.sh`
6. `curl -v -x socks5://123456:@localhost:9999 https://www.google.com`

**Actual behavior**
Request won't succeed. In logs you may see something like this:
```
yamux: Invalid protocol version: 22
```
Note: the number may differ between runs. Happens for both DMSG and STCP tps

**Expected behavior**
Request succeeds

**Comment by jdknives** [comment]
Cannot be reproduced.
