### ISSUE TITLE
Undefined log.Writer

### ISSUE THREAD

**Issue by mikecummings34** [skycoin/skywire#241]
When building...in a hurry so posting this now just in case this is a bug. Need to double check my go version.
![Annotation 2020-03-23 215810](https://user-images.githubusercontent.com/35720426/77386901-9c488b80-6d51-11ea-9f96-67f8d0dfa91c.png)

**Comment by evanlinjin** [comment]
This is not a bug. Please check your go version. It clearly states: `note: module requires Go 1.13`
