### ISSUE TITLE
Refactor config structs to make a proper use of README generator

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire#244]
**Feature description**
Currently we have a README file generator, but we can't use it right now, cause structs need to be refactored first. The main thing to do is to get rid of the anonymous structs - all structs should have dedicated named types. After that we may generate README's for all the config files. Also adding a Makefile target would be useful for that

**Comment by nkryuchkov** [comment]
@Darkren I got rid of some anonymous structs in my PR https://github.com/SkycoinProject/skywire-mainnet/pull/246. I've just checked it and it looks to me like there's no anonymous struct in configs anymore. Could you please check if I'm right or wrong? Thank you.
