### ISSUE TITLE
Cannot use dmsgpty in manager UI

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#248]
**Describe the bug**
I cannot run the dmsgpty-terminal in the UI. I setup a visor and a hypervisor, accessed the UI and went to Terminal>Full Terminal. 

It returns `SSL_ERROR_RX_RECORD_TOO_LONG`. The issue is that the UI tries to call https://localhost. When I enter the URL without https and use http instead, everything runs smoothly. 

I rememeber distantly, that we discussed this issue before. It needs to be fixed either by making https work or by disabling https.

**Comment by Senyoret1** [comment]
During some tests I made today I saw that the `SSL_ERROR_RX_RECORD_TOO_LONG` appeared when the ssl settings were empty in the hypervisor configuration file. May be that is related to this issue.

**Comment by jdknives** [comment]
Fixed by #258
