### ISSUE TITLE
Disallow starting `skywire-visor` when another instance is running.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#261]
**Describe the bug**
For some users of [`skybian`](https://github.com/SkycoinProject/skybian), it is tempting to run `skywire-visor`, although `skywire-visor` is already running as a systemd service.

Currently, we are allowing this behavior, hence, making the `skywire-visor` service malfunction.

**Possible implementation**
Currently, when we start `skywire-visor`, we delete the existing unix files. We should disable this action unless `--force` flag is set.

**Comment by nkryuchkov** [comment]
The following should be considered in the implementation of this feature:

In the current implementation of the updater, after downloading, it creates a new `skywire-visor` process passing a `--delay` argument that asks `skywire-visor` to start with delay. Then the old process exits. So, there may be 2 instances running simultaneously for a short time.

So, I think, we might just check for another instance _after_ delay, but _not before_ it.

**Comment by jdknives** [comment]
Will close this for now. Users are not encouraged to access the dmsgpty or ssh into their nodes atm unless there are clear instructions provided in docs. We cannot and should not try to prevent any misusage or configuration.
