### ISSUE TITLE
Implement a holepunch transport

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#264]
> We need a transport that uses a point to point connection between two parties that are behind firewalls.
> 
> There are standard protocols that we should be able to use. The main one is called ICE.

**Comment by Jeff-Bouchard** [comment]
I saw a Blockchain project use STUN Protocol pass-through Firewalls
there's a list of a hundred or so random  STUN servers. Perhaps this comment will spark a better idea

**Comment by jdknives** [comment]
Fixed by #313
