### ISSUE TITLE
Visor version not displayed

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#269]
**Describe the bug**
In the manager UI, the node version (which should be renamed to visor version) is not displayed (it is empty). It should be displayed in the appropriate field in the visor overview page. I am not sure whether we have an endpoint for getting the visor version.

**Comment by nkryuchkov** [comment]
Just FYI: the version can be fetched using `/visors` or `/visors/{pk}` endpoints. It's located under the `build_info` section, and then `version`.

**Comment by jdknives** [comment]
Fixed by #272
