### ISSUE TITLE
Add an API endpoint to the hypervisor for checking the config of the apps

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#270]
**Feature description**
It is possible to change the config of the apps with the `/api/visor/{key}/apps/{app}` API endpoint, but the hypervisor does not have an endpoint for checking the current config of an app. This means that the manager UI can show options for changing the config, but the user will always see empty forms, which is not very good for the UX, as the expected behavior is to see the form filled with the current config.

**Describe the solution you'd like**
Add an API endpoint for checking the current config of an app. However, some care would be needed with sensitive data, like passwords.

**Comment by jdknives** [comment]
@Senyoret1 just merged. I think you can work on the frontend for that.
