### ISSUE TITLE
Skysocks client interrupts connection

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#280]
**Describe the bug**
The `skysocks client` establishes connection to server properly (it seems), but throws error and cannot be used. (See attached logs

**Environment information:**

- OS: e.g. MacOS

**Steps to Reproduce**

1. Setup two visors on separate machines
2. Connect them via dmsg transport
3. Setup skysocks client
4. Connect skysocks client to skysocks server

**Actual behavior**
The client throws errors as seen in the logs and cannot be used. The browser reports that the proxy has refused a connection. The proxy reestablishes a route after the failure, which in turn, fails again. 

**Expected behavior**
Proxy should work. 

[message.txt](https://github.com/SkycoinProject/skywire-mainnet/files/4410385/message.txt)

**Comment by nkryuchkov** [comment]
Commit `b57b9821c819f78b46cdfe7f9ebacb6ba000e0b9`

**Comment by jdknives** [comment]
Fixed by #291
