### ISSUE TITLE
Dmsgpty UI does not work in Safari

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#344]
**Describe the bug**
When opening up the dmsgpty UI in Safari it just shows a blank black screen. The UI works in Firefox. 

**Environment information:**

- OS: Mac OS X
- Safari Version 13.1 (15609.1.20.111.8)

**Steps to Reproduce**

1. Run interactive env
2. Open hypervisor
3. Open fuill terminal

**Actual behavior**
<img width="1113" alt="Bildschirmfoto 2020-04-22 um 11 36 08" src="https://user-images.githubusercontent.com/36450093/79980902-14ff4c80-84a4-11ea-82f0-0bd14e3aa782.png">

**Comment by mrpalide** [comment]
Dmsgpty for both local hypervisor (on Monterey 12.3.1) and remote visor (on Ubuntu 20.04) by fully terminal accessible from Safari v15.4 (17613.1.17.1.13).
![image](https://user-images.githubusercontent.com/79150699/168590559-ccb851d0-7cea-4cf5-b160-b3a20da925c7.png)
