### ISSUE TITLE
Give app an ability to request config changes from the visor

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire#345]
**Feature description**

Apps should be able to request config changes from the visor. This may done as discussed on Discord:

```
i think the best solution is if we add a function in appserver.RPCGateway along the lines of func (g *RPCGateway) Value(name string, v interface{}) error
```
but also, thinking further, it might not work well with the nested values. probably should be thought of deeper

**Comment by evanlinjin** [comment]
@Darkren If we have:
```golang
func (g *RPCGateway) Value(name string, v []byte)
```
And have v as an encoded JSON object, would that solve the nested values problem?

**Comment by Darkren** [comment]
@evanlinjin if we request the top level object, yes, this will do
