### ISSUE TITLE
Hypervisor is not retrying discovery registration

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#346]
**Describe the bug**
@evanlinjin reported that the hypervisor did not retry registering itself in the dmsg.Discovery and therefore visors could not connect. 

The hypervisor should try to register itself in the discovery continually with a backoff.

**Comment by evanlinjin** [comment]
These seems to be not a problem with the latest version of `skywire-mainnet`. I also had a brief look into this, and it seems that the logic for this is in the `dmsg` repo.

**Comment by evanlinjin** [comment]
I've also experienced visors disconnecting from hypervisor after a certain time period. The only way to fix this is to restart hypervisor.

**Comment by jdknives** [comment]
@evanlinjin will investigate the disconnection issue a bit and delete the issue if I cannot reproduce it for now. From previous experience I would say this looks like a Skybian issue if it exists at all.

**Comment by evanlinjin** [comment]
@jdknives Personally I don't think this issue is Skybian-dependent. Seems like something went wrong in dmsg, or we need some acknowledgement logic to ensure no disconnection.

**Comment by jdknives** [comment]
Closed by #349
