### ISSUE TITLE
Visor doesn't show up in hypervisor UI after binary update

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#350]
**Describe the bug**
Visor doesn't show up in hypervisor UI after a binary update. A reboot fixes that.

**Environment information:**

- Skyminer

**Steps to Reproduce**

1. Run `/update`

**Actual behavior**
Visor doesn't show up in hypervisor UI after a binary update.

**Expected behavior**
Visor shows up in hypervisor UI after a binary update.

**Additional context**
Logs:
[visor03update.log](https://github.com/SkycoinProject/skywire-mainnet/files/4545122/visor03update.log)

**Possible implementation**
Likely, it's not `Skyminer`-dependent

**Comment by evanlinjin** [comment]
It might be a good idea to be able to configure the *restart mechanism*. Looking at the logs, the forked process is no longer tracked by `systemd`.

To fix this, I propose to have an additional field on `visor-config.json`: `restart_mode` which takes in a string.

Options can be:
- `forked`
- `systemd`

If `"restart_mode": "systemd"` is defined, `systemd restart skywire-visor.service` should be run instead of the usual `forked` process mode.

**Comment by evanlinjin** [comment]
As the `skywire-visor.service` has `Restart=on-failure` set: https://github.com/SkycoinProject/skybian/blob/847accf1f3cd2a1d7e38fb79af2884f0bddd5af4/static/skywire-visor.service#L10

Another hack would be to exit with non-zero exit code and systemd will do the honors.

**Comment by nkryuchkov** [comment]
@evanlinjin Checking if a process is run by `systemd` is a great idea. However, `skywire-visor` also needs to know if it should start a new process, so I'm not sure whether the hack would work. I would suggest checking if a parent PID equals to `1`. In this case, a process is run by `systemd`. I think this might be more robust than config because configs are made by humans.

**Comment by evanlinjin** [comment]
> @evanlinjin Checking if a process is run by `systemd` is a great idea. However, `skywire-visor` also needs to know if it should start a new process, so I'm not sure whether the hack would work. I would suggest checking if a parent PID equals to `1`. In this case, a process is run by `systemd`. I think this might be more robust than config because configs are made by humans.

That sounds like an even better idea.

**Comment by jdknives** [comment]
Fixed by #380
