### ISSUE TITLE
Add a way to configure the port of the skysocks-client app

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#354]
**Feature description**
Currently the `PUT api/visors/{{pk}}/apps/skysocks-client` API endpoint allows to change the public key used by the skysocks-client app, but not the port. This is an important problem because the Skywire manager uses the proxy discovery service for allowing the user to select a remote visor to connect to and the `PUT api/visors/{{pk}}/apps/skysocks-client` API endpoint to change the configuration of the app, but that service returns not just the public key, but also the port, and there is no way for using that port via the API.

**Is your feature request related to a problem? Please describe.**
An option is to add a new param to the API endpoint.

**Describe alternatives you've considered**
Long term, adding app specific params to a generic endpoint like `PUT api/visors/{{pk}}/apps/{{app-name}}` may be problematic. But as a short term fix it may work.

**Comment by jdknives** [comment]
@Senyoret1 it is not really expected that the skysocks server would run on a port other than 3 so strictly speaking, we do not need to display that at all yet. The port number will be relevant when we have non-default apps running and advertising themselves. We can omit the port for now in the hypervisor.

**Comment by Senyoret1** [comment]
Oh, ok. I added the changes to the PR: https://github.com/SkycoinProject/skywire-mainnet/pull/326#issuecomment-622466761 . this issue is not longer needed then.
