### ISSUE TITLE
Set up sorting imports correctly

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#361]
**Feature description**

We run `goimports` in `make format` which sorts imports. However, it does not group them correctly. The right order is:

1. Standard library imports
2. 3rd party libraries
3. Current project imports.

We need to find a way to sort them in the correct order automatically.

**Comment by jdknives** [comment]
https://github.com/incu6us/goimports-reviser is not usable.

**Comment by jdknives** [comment]
@nkryuchkov maybe it would make sense to raise an issue with `goimports-reviser`.

**Comment by nkryuchkov** [comment]
@jdknives It looks like https://github.com/incu6us/goimports-reviser works great now. Let's test it.

**Comment by nkryuchkov** [comment]
WIll be closed by all referenced PRs.
