### ISSUE TITLE
Get back `-t` flag for `skywire-cli visor gen-config`

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire#365]
**Describe the bug**
There was previously an ability to generate test config for visor with `skywire-cli visor gen-config -t`. This flag was accidentally removed by latest changes and should be returned.

**Comment by jdknives** [comment]
@evanlinjin It might make sense to also include our new uptime tracker for test deploy in the test env constants. The domain used is 

`uptime-tracker.skywire.cc`
