### ISSUE TITLE
Expose an RPC interface from a skywire app that the visor can call.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#370]
**Feature description**

There are certain use cases where a visor may wish to communicate with a skywire app in which the communication is initiated by the visor (and not the skywire app): i.e. https://github.com/SkycoinProject/dmsg/issues/93

In the above example, the visor will wish to initiate some sort of communication with the VPN app within the `SessionPreDialCallback` and `SessionDisconnect` callbacks.

**Is your feature request related to a problem? Please describe.**
* https://github.com/SkycoinProject/dmsg/issues/93

**Possible implementation**
We need to have the `app.Client` host an RPC interface that is only advertised to the visor.
To do this, we can reuse the proc key to be the name in which the RPC object is registered as.

A possible gateway implementation is as follows:
```golang
type RPC struct{ /*TODO*/ }

type Event struct {
    Name string // event name
    Data  []byte
}

type EventResp struct {
    Ok    bool
    Data []byte
}

func (rpc *RPC) OnEvent(e *Event, resp *EventResp) error { /*TODO*/ }
```

In which the app client has a go routine that handles the incoming events.

**Comment by jdknives** [comment]
Closed
