### ISSUE TITLE
Move the 'buildinfo' module to 'dmsg' repo.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#373]
**Describe the bug**
As mentioned on [Discord@714450955713904721](https://discordapp.com/channels/466450852098605059/466450852098605061/714450955713904721):
> We should probably move `buildinfo` into [`dmsg`](https://github.com/SkycoinProject/dmsg) to avoid possible cyclic dependencies...

![Screenshot.](https://cdn.discordapp.com/attachments/466450852098605061/714450954916855839/unknown.png)

**Comment by jdknives** [comment]
Fixed by above PR.
