### ISSUE TITLE
Config naming convention

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#386]
**Feature description**

There were various request from @SkycoinSynth to change some of the config fields to improve clarity. 

- [ ] change `port` to `dmsgport`

- [ ] rename `trusted visor` to `autopeering`

- [ ] rename `local address` to `listenting address` and fill it with ":7777" by default. 

- [ ] change `stcp` to `skywire-tcp`

**Comment by nkryuchkov** [comment]
We also need to change `launcher.discovery.proxy_discovery_addr` to `launcher.discovery.service_discovery_addr`.
