### ISSUE TITLE
Copy Pubkey button

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#388]
**Feature description**

It would be nice to have a copy paste button like inside the visor details when seeing hypervisor list. 

**Is your feature request related to a problem? Please describe.**
When I try to mark and copy the pubkey in the visor list I get directed to the visor instead of just marking the pubkey.

**Comment by jdknives** [comment]
@4rchim3d3s you would want a copy button here?
<img width="1440" alt="Bildschirmfoto 2020-06-03 um 11 04 14" src="https://user-images.githubusercontent.com/36450093/83611719-0cf9f880-a58a-11ea-8826-c132db7e5dde.png">

**Comment by 4rchim3d3s** [comment]
Yes, like this for example (with better coloring, just copied from visor):

![image](https://user-images.githubusercontent.com/50741854/83613015-775b6a80-a583-11ea-9464-ef9c3dddfce9.png)

Also the labeling is lost everytime hypervisor gets restarted, but I think this is a known issue

**Comment by jdknives** [comment]
@4rchim3d3s Copy. Thats not a know issue actually. I have not encountered it so far. Will try to reproduce it.

**Comment by 4rchim3d3s** [comment]
Just had a deeper look into it.
The label gets lost the moment i close my firefox tab and go to localhost:8000 again.
I use Firefox in privacy mode.
Tried with google chrome and there it works, so the labeling is saved inside cookies or something like that? 

Maybe would be helpful to save the labeling inside the visor, when using two different hypervisors you have to label every visor again. On the other hand maybe you want to label it different on the two hypervisors. How about a **custom label** / **hypervisor label** (saved in hypervisor and unique to this hypervisor) and a **visor label** (saved on visor and therefore the same on two different hypervisors)?

So you would have to have two label columns inside the visor list

**Comment by jdknives** [comment]
@4rchim3d3s that explains it. Will think about something like that. Not sure whether it makes a lot of sense to have different label types or store labels on visors.
