### ISSUE TITLE
Update message (what's new + link to release information)

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#396]
**Feature description**

Now when clicking on update we get this message:
![image](https://user-images.githubusercontent.com/50741854/84028710-81b9a200-a991-11ea-9e2b-3c4c11704d8e.png)

I know this is a testing release but it would be great to always have infos inside this message about what new features got added. Something like the changelog here:
![image](https://user-images.githubusercontent.com/50741854/84028928-dd842b00-a991-11ea-9e55-fb1e16332216.png)
 and a link (https://github.com/SkycoinProject/skywire-mainnet/releases/tag/v0.2.4-test-4bacd5e0) to more information.
Displaying only the link I think is easier than the whole changelog and may also be enough.

I guess this is not that much implemented yet, as there at the moment there should be a warning that this update should not be installed yet in this message. (Maybe will never be a problem in the future when the update mechanism is working.

Also the way the message is displayed is a lot of text. How about this format?:

**Currently Installed:** v0.2.3 (releasedate)
**Available update:&nbsp;&nbsp;&nbsp;**   v0.2.4 (releasedate) [new features](https://github.com/SkycoinProject/skywire-mainnet/releases/tag/v0.2.4-test-4bacd5e0)

***Unstable update:** v0.2.4-test (releasedate) (handle with care)*

**Comment by jdknives** [comment]
Partially handled here github.com/skycoin/skywire/pull/475

**Comment by jdknives** [comment]
Fixed with #506
