### ISSUE TITLE
visor does not connect to / apppear in hypervisor on other side of router

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#398]
**Describe the bug**
the visor does not appear in the hypervisor when the hypervisor is on the other side of the (official skyminer) router

**Environment information:**

- OS: Archlinux, ArchlinuxARM
- Platform: x86_64, aarch64
(desktop, official skyminer)

**Steps to Reproduce**
Using the official skyminer (with port forwarding previously configured on the router)-
* install skywire on desktop (x86_64) and skyminer
(freshly built to the latest commits to master today)
* generate hypervisor and visr configs
* copy hypervisor public key into visor config
* start visor and hypervisor

**Actual behavior**
Visor does not appear in hypervisor interface. Visor's terminal output indicates "dialing" the hypervisor public key repeatedly.

**Expected behavior**
Visor appears in hypervisor interface.

**Additional context**
My guess is that the router is blocking the connection.

it was my understanding that this was supposed to work, from this article of documentation
https://github.com/SkycoinProject/skywire-mainnet/wiki/Run-HypervisorUI-on-local-machine

**Comment by jdknives** [comment]
@0pcom Are you sure that both the visor and the hypervisor use the same deployment? So are you sure the hypervisor was using the production deployment (and consequently that you did not use the `-t` flag) Can you check give us the logs for the hypervisor and visor in question? Sounds like a configuration or dmsg issue. As long as both visor and hypervisor have an internet connection, everything should work regardless of router configuration.

**Comment by 0pcom** [comment]
I have not had time to conduct further tests. I am reasonably certain that the -t flag was not used but I will verify this the first chance I have.

**Comment by jdknives** [comment]
Cannot reproduce this so will close for now.
