### ISSUE TITLE
Visor fails to start if connection to address resolver cannot be established.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#401]
**Describe the bug**

Whether visor starts all not should not depend on whether address resolver is up or down.

Ideally, visor should still start, but it logs the connection error. Afterwards, it attempts to connect to the address resolver via exponential backoff.

If the aforementioned is difficult to implement, maybe another temporary solution would be to block until the connection to the address resolver can be established.

**Comment by jdknives** [comment]
Similarly, we need to fix the currernt behavior of the tp-disc client. If it fails to establish a connection to the tp disc, the visor fails to start.

**Comment by jdknives** [comment]
Partially fixed by #402
