### ISSUE TITLE
Move syslog to dmsg repo.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#404]
Package `/pkg/syslog` should be moved to https://github.com/SkycoinProject/dmsg as it is commonly used.

**Comment by jdknives** [comment]
@evanlinjin only could find this imported in `skywire-services`. Am I missing any references? If not, I will close this.

**Comment by evanlinjin** [comment]
@jdknives That is correct, but it should be used in `dmsg` and `skywire` services IMO.
