### ISSUE TITLE
Metrics for setup-node.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#405]
We need [Prometheus](https://prometheus.io/) metrics reporting for `setup-node`.

### Metrics
- [x] Gauge for ongoing request count.
- [x] Histogram for request duration.
- [x] Counters for failed and successful requests.

**Comment by devzone777** [comment]
@evanlinjin I was planning to build a prometheus exporter. Does one exist already? If not I can start working on it now.

**Comment by evanlinjin** [comment]
> @evanlinjin I was planning to build a prometheus exporter. Does one exist already? If not I can start working on it now.

Where were we planning to export metrics data to?

**Comment by devzone777** [comment]
> > @evanlinjin I was planning to build a prometheus exporter. Does one exist already? If not I can start working on it now.
> 
> Where were we planning to export metrics data to?

@evanlinjin where Grafana is running currently with existing Prometheus DB, or spin up another instance if need be

**Comment by evanlinjin** [comment]
@devzone777 Yes, that will be helpful. We need some intuitive way of displaying this data. The old Grafana deployment does not have this set up to be easy to use.

**Comment by jdknives** [comment]
@evanlinjin @devzone777 I will make a new ticket for visualizing the metrics we collect. It may be wise to speak with Murphy about this as he setup Grafana for the current prod deployment.
