### ISSUE TITLE
HypervisorUI dmsg tab

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#407]
**Feature description**

@skycoin-main requested that we add a `dmsg` tab to the landing page of the hypervisor UI. This tab should display:

The visors connected to the hypervisor (same list as in the Visor list tab). Below each visor, the UI should display the PubKey of the dmsg.Server used to connect to the visor as well as the Ping roundtrip time. 

Requires: https://github.com/SkycoinProject/dmsg/issues/110

**Comment by jdknives** [comment]
@Senyoret1 Evan implemented the backend for this in #415 . Would you mind integrating that with the Hypervisor frontend?

**Comment by Senyoret1** [comment]
@jdknives I already checked the changes made to the backend and I was wondering if a new tab is really needed. The current visor list could be modiffied to show the new data and it is also possible to add a button for hidding the extra data. This would avoid having 2 lists wich are basically the same, which could be confusing

**Comment by jdknives** [comment]
@Senyoret1 good point. It does not have to be a separate tab if you are able to integrate this data in the visor list.
