### ISSUE TITLE
Logrus is slow, consider using an alternative.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire#411]
**Feature description**

https://github.com/uber-go/zap
https://github.com/rs/zerolog

**Comment by jdknives** [comment]
@evanlinjin is there any problem this solves or prevents in the future? The benchmarks look nice, but I have not heard of any instance in which the performance of logrus is an actual issue.

**Comment by evanlinjin** [comment]
@jdknives This is only a potential issue, I haven't looked greatly into it.
