### ISSUE TITLE
Add UI/UX improvements to the manager

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#429]
**Feature description**

Describe the feature
This is a list of improvements that can be done to improve the UI and UX of the Skywire manager:

- [x] If the user has too much data of a single type (visors, transports, routes or apps), the manager UI should show a search option, for being able to find the desired element easily.
- [ ] The manager should show more data in the routes list, as it is currently only showing the rule, which is not a friendly data for the user.
- [x] Show a paginator in the visor list if there are too many visors, just like it happens with the transport list.
- [x] The tab changes should be saved in the navigation history, to be able to return to the previous tab with the back button, as the current behavior is a bit confusing.
- [x] A method for reusing the node data should be added to the node details page, to avoid having to reload all the data each time the active tab is changed. This would improve the navigation.
- [x] Add a button for removing all offline nodes, as the manager keeps them in the list waiting for them to be online again.
- [x] Create a procedure for updating the network traffic graphs in constant intervals, as the current method refresh the graphs each time the page data is refresed, which is very inconsistent.
- [x] Add help icons with information about the data shown by the manager in different parts. This would allow new users to quickly underestand concepts like "transports" and "routes", which are specific for Skywire and may be confusing for new users.

**Comment by Darkren** [comment]
hey there @Senyoret1 you may get some route info from this endpoint: `/visors/{pk}/apps/{app}/connections`

**Comment by jdknives** [comment]
Fixed by #436 and #645
