### ISSUE TITLE
Automate trusted visor functionality

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#431]
**Feature description**

Automate trusted visor functionality

**Describe the solution you'd like**

We can register the trusted visors in the service discovery and every user that sets up a visor on public IP can register there.

**Additional context**
We need to have checks of some sort to prevent someone from accidentally registering their visor in service discovery if they are not on public IP. This may be done by sending an HTTP request from service discovery to visor to check availability.

**Comment by evanlinjin** [comment]
> We need to have checks of some sort to prevent someone from accidentally registering their visor in service discovery if they are not on public IP. This may be done by sending an HTTP request from service discovery to visor to check availability.

It will be good to have this functionality for `dmsg.Server` too. Left a comment here for future reference.
