### ISSUE TITLE
Encryption Module

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#432]
**Feature description**

The VPN encryption currently relies on a keypair specified within the config fields for the VPN. It would improve usability a lot if we would use the local visors keypair for encryption. Maybe it makes sense to move encryption to its own module within router for instance to e2e encrypt all route traffic instead of doing encryption on an application level. 

**Is your feature request related to a problem? Please describe.**
It is hard to setup encryption for the VPN at the moment.

**Comment by evanlinjin** [comment]
I remember Synth stating that encryption should be at the *transport level* as Skywire is meant to be encrypted by default.

**Comment by devzone777** [comment]
@evanlinjin That would be wise to do, so that the network doesn’t become “leaky”.
Also would relieve future app devs from having to build out e2e encryption in most cases.
