### ISSUE TITLE
Normalize updates

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#449]
**Feature description**

The current system of updating via the UI button does not update the system software.

It updates the skywire 'installation' which is a term I use loosely. This is not ok to do if you have installed skywire as a package, and instead of the desired effect of the updates happening the way you want them to, stuff is overwritten in an arbitrary way, and the package manager is disregarded.

For updates to the system software to be done correctly and as automatically as possible, there must remain room for manual intervention, which the current system does not facilitate and which is not an unexpected or irregular occurence.

###Outline of ideal update interaction:
* UI button is clicked to update an individual visor
* full dmsgpty terminal window opens in web browser and a full system update is initiated
* The system update completes with success and the window closes
* The visor should reboot if the linux kernel was updated

Most importantly, the window should not close if the exit status of the update command was not 0 so that the administrator can act to fix things. This is what is termed 'manual intervention' and it remains a fact of life on any linux distribution.

**Is your feature request related to a problem? Please describe.**

Totally solves all current installation and updating issues.
This relates to / encompasses #387

**Describe the solution you'd like**

The idea when phrased differently is to adapt [yay](https://github.com/Jguer/yay) to work on other linux distributions in some way or other. This is where the magic happens with dependency management. Yay is beautifuly written in golang and it is, I believe, the most widely used AUR package and the first one that most people who use Archlinux will install from the AUR.

To summarize the features specifically needed to create a reliable updater as I have described:

* Recognise what linux distribution it is running on
* Provide an interface to the system package manager
* interactive search/install
* Minimize user input
* Automate local package creation from [AUR](aur.archlinux.org) or custom repo hosting builds
* dependancy management

[yay](https://github.com/Jguer/yay) has most of this, and there are other tools which could be ported from arch to make creation of packages easier.

**Describe alternatives you've considered**

It would be an equally valid thing to do to eliminate the updater entirely and let the administrator install skywire via a package. The system could be updated normally from the dmsgpty terminal with instructions for how to do so

**Possible implementation**

If the dmsgpty terminal can open and run a command I can come up  with the specific implementation for updates which will encompass the existing packaging efforts.

**Comment by jdknives** [comment]
@0pcom this has been solved with #911 I guess. Users are instructed to update the package themselves if they have installed via package managers and directed to the official ressources if they installed a package we provide.

**Comment by jdknives** [comment]
Let me know any further concerns you may have.

**Comment by jdknives** [comment]
Two more comments:

1. The auto update of system dependencies and automatic pop up of the dmsgpty is not going to be implemented. For average users we provide simple installers (MacOS and soon Windows). People running deployments should be able to implement their own solutions and we should not try to offer a failsafe solutions for them. Users wil be directed to update with their package manager if the installation is detected as package based installations. 
2. The exception to that is Skybian as requested by @skycoin-manager . We will provide a one click update for Skybian as we have been previously.
