### ISSUE TITLE
Merging into master breaks production deployment

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#461]
**Describe the bug**
The production deployed of `uptime-tracker` is not branched from `master` and was deployed manually. Hence, the production deployment gets broken or merging to `master`. The changes introduced in the `develop` branch fixing the `uptime-tracker` behavior should be merged into the `master` branch to be able to create pull requests against `master`.

**Comment by jdknives** [comment]
Should be fixed.
