### ISSUE TITLE
Problems for configuring apps with the hypervisor API

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#469]
**Describe the bug**
If you try to configure the skysocks-client or the skysocks app using the hypervisor API, the operation will end with an error.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**

1. Start some nodes with `make integration-run-proxy`.
2. Call `PUT https://localhost:4200/api/visors/031b80cd5773143a39d940dc0710b93dcccc262a85108018a7a95ab9af734f8055/apps/skysocks-client` with `{"pk":"024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7"}` as arguments, to try to change the public key of the proxy. It will return `rpc: can't find method app-visor.SetSocksClientPK`.
3. Call `PUT https://localhost:4200/api/visors/024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7/apps/skysocks` with `{"passcode":""}` to try to change the password. It will return `failed to start skysocks: fork/exec bin/apps/skysocks: no such file or directory`

**Actual behavior**
The operations fail.

**Expected behavior**
The aperation should finish without problems and the configuration should be updated.

**Additional context**
The apps appear as running in the manager.

**Comment by jdknives** [comment]
@Senyoret1 seems to me to be closed by #471 Reopen if there are further issues.
