### ISSUE TITLE
TravisCI build for OS X fails constantly

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#482]
**Describe the bug**
TravisCI builds for OS X fail constantly after executing `Compiling @ngx-translate/core : es2015 as esm2015` in `make lint-ui`.

**Environment information:**

- TravisCI, OSX

**Steps to Reproduce**

1. Do anything that makes TravisCI create a build.

**Actual behavior**
Build fails.

**Expected behavior**
Build succeeds.

**Additional context**
I don't remember this error before the recent update of Angular. But I may be wrong here. The issue might be related to the update or to the `ngx-translate/core` dependency.

**Possible implementation**
@Senyoret1 had an idea of updating `ngx-translate/core` to the latest version.

**Comment by Senyoret1** [comment]
After some testing, the problem turned out to be because Travis is using MacOS 10.11. If you change `osx_image: xcode8` to `osx_image: xcode8.3` in the `.travis.yml` file it works

**Comment by nkryuchkov** [comment]
@Senyoret1 Thanks. Let's try that.

**Comment by nkryuchkov** [comment]
@Senyoret1 That fixed the issue. Great.
