### ISSUE TITLE
Build failing at go mod vendor -v

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#502]
**Describe the bug**
build fails at vendorcheck

**Environment information:**

- OS: Linux

**Steps to Reproduce**:

1. clone repo
2. `make build`

**Actual behavior**
 $ make build
GO111MODULE=on go mod vendor -v
go: github.com/skycoin/dmsg@v0.0.0-20200803194104-78ff5746d8a3 requires
        github.com/skycoin/skywire@v0.2.3-0.20200803142942-0f8b9981f6f9 requires
        github.com/SkycoinProject/dmsg@v0.2.0: reading github.com/SkycoinProject/dmsg/go.mod at revision v0.2.0: unknown revision v0.2.0
make: *** [Makefile:110: dep] Error 1

**Expected behavior**
build ducceeds

**Comment by jdknives** [comment]
Fixed by above PRs.
