### ISSUE TITLE
Skywiremob fails if stopped before setting a socket

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#511]
**Describe the bug**
If a visor is started with Skywiremob and stopped before creating a socket for connecting the visor and the app, the visor fails and the app is force closed.

**Environment information:**

- OS: Android 5 to 10 (x86 emulator).
- Platform: Android 5 to 10 (x86 emulator).

**Steps to Reproduce**

1. Start a node with Skywiremob, to the point in which `Skywiremob.isVPNReady()` returns `true`.
2. Without creating a socket for connecting the visor with the app, call `visor.stopVisor()`

**Actual behavior**
Skywiremob will panic with an error like this:
```
E/Go: panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa222c057]
    goroutine 122 [running]:
    net.(*UDPConn).Read(0x0)
    	<autogenerated>:1 +0x17
    io.copyBuffer(0xaf4a3050 ...)
    	c:/go/src/io/io.go:402 +0xe4
    io.Copy(...)
    	c:/go/src/io/io.go:364
    github.com/skycoin/skywire/internal/vpn.(*ClientMobile).Serve.func2(0x81f92480)
    	C:/GoPath/src/github.com/skycoin/skywire/internal/vpn/client_mobile.go:68 +0xb5
    created by github.com/skycoin/skywire/internal/vpn.(*ClientMobile).Serve
    	C:/GoPath/src/github.com/skycoin/skywire/internal/vpn/client_mobile.go:65 +0x10e
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4219 (ire.skycoin.vpn)
Disconnected from the target VM, address: 'localhost:8647', transport: 'socket'
```

**Expected behavior**
The visor should be stopped without problems.

**Comment by Darkren** [comment]
Hey there @Senyoret1 ! just updated #447 , please try it out. also there's one trouble there. when `isVpnReady` gets true and we push `stop`, visor now gets shut down properly. but vpn service might be being started. so, when we push `stop` we need to ensure that all the mobile facilities are closed properly. I'm having issues with debugging the app, so probably my issue is artificial and won't happen for a real user. anyway, please try it out and tell me if there are issues left

**Comment by Senyoret1** [comment]
It works well, thank you. The version of the Android app I’m working on manages the service closure, so there should not be problems.
