### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#527]
https://travis-ci.com/github/skycoin/skywire/jobs/385888890
https://travis-ci.com/github/skycoin/skywire/jobs/385888891

**Comment by nkryuchkov** [comment]
https://travis-ci.com/github/skycoin/skywire/jobs/385888890 seems to be a connection issue. Fixed by restarting the build.

**Comment by jdknives** [comment]
Should be fixed by #530
