### ISSUE TITLE
Avoid indirect links for go modules 

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#541]
Currently go.mod lists a few dependencies such as 

- boltdb
- nhooyr
- wireguard

with indirect links that redirect to Github repositories of the dependency. (nhooyr.io/websocket redirects to https://github.com/nhooyr/websocket) If possible, we should use the direct links in the first place instead of the indirect links. @SkycoinSynth suspects that using indirect links increases the likelihood that things could break for Chinese users otherwise.

**Comment by nkryuchkov** [comment]
GitHub repositories of the listed dependencies contain `go.mod`s declaring no GitHub repository as module:

https://github.com/nhooyr/websocket/blob/master/go.mod#L1
https://github.com/etcd-io/bbolt/blob/master/go.mod#L1
https://github.com/WireGuard/wireguard-go/blob/master/go.mod#L1

Therefore, when using GitHub repositories as imports, `go mod` returns errors like this:
```
go: github.com/nhooyr/websocket@v1.8.2: parsing go.mod:
        module declares its path as: nhooyr.io/websocket
                but was required as: github.com/nhooyr/websocket
```
