### ISSUE TITLE
Reusable UT client connections

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#551]
We should check if UT client connections should be reused in order to increase performance.

**Comment by taras-skycoin** [comment]
We already use *http.Client which reuse TCP connections by default. To check locally if it true you can run this command 
``` sudo tcpdump -vnnSX port 9095 -i lo``` and check if a port is persistent between requests. 

Also, you can run a few times this command:  `ss -t | grep 9095` and check if  randomized, complementary port is the same all time.
