### ISSUE TITLE
Error while updating service discovery entry

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#557]
**Describe the bug**
```
[2020-10-19T11:06:34Z] WARN [app_discovery]: Failed to update service entry in discovery. Retrying... appName="vpn-server" error="Post "http://service.discovery.skycoin.com/api/services": http: ContentLength=192 with Body length 0"
```

**Steps to Reproduce**

1. Run `skywire-visor` with VPN server enabled
2. Wait for a couple of minutes

**Actual behavior**
The error above is returned.

**Expected behavior**
No error in logs.

**Additional context**
It might be an issue in `httpauth` when `(*http.Request).Do` is called after request body is already read.

**Comment by jdknives** [comment]
Fixed by #558

**Comment by jdknives** [comment]
Issue actually persists.

**Comment by nkryuchkov** [comment]
New error:
```
Failed to update service entry in discovery. Retrying... appName="skysocks" error="json: cannot unmarshal object into Go struct field HTTPError.error of type string"
```
