### ISSUE TITLE
Update Hypervisor outputs -unknown instead of version

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#563]
**Describe the bug**
![image](https://user-images.githubusercontent.com/50741854/96507119-075f2f80-1259-11eb-93cc-3905c8167e96.png)

**Environment information:**

- OS: Ubuntu,
- hypervisor: v.0.3.0

**Steps to Reproduce**
Try to update Hypervisor via UI

**Actual behavior**
shows -unknown

**Expected behavior**
show - 0.3.0

**Comment by jdknives** [comment]
Will close this as the next release gets rid of a separate hypervisor binary and the update hypervisor call will not be necessary anymore.
