### ISSUE TITLE
Add new flag to config-gen

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#567]
**Feature description**

Add a flag to `skywire-cli visor gen-config` that generates a config against production that specifies `apps` and `local` as a relative path to the directory that the command is called in. 

**Is your feature request related to a problem? Please describe.**
On branch `feature/v0.4.0`, skywire-cli generates a config that specifies the app binaries and `local` files to be located in `/opt/skywire` when not called with `-t` flag. When we want to test something against prod deployment, that means we either have to move `app` and `local` dir to `/opt/skywire` or manually change config.

**Comment by nkryuchkov** [comment]
Overridden by https://github.com/skycoin/skywire/issues/572
