### ISSUE TITLE
Dmsg Ping does not work on `feature/0.4.0

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#568]
**Describe the bug**

On branch `feature/0.4.0`, using the prod deployment, the DMSG ping does not work but only displays `-1ms`. I would assume this is related to the hypervisor being merged into visor as it works on `develop`.

**Environment information:**

- OS: Mac OS X

**Steps to Reproduce**

1. Go to `feature/v0.4.0`
2. Run `skywire-cli visor gen-config -r --hypervisor`
3. Run visor
4. Check visor page of the visor on localhost:8000

**Comment by nkryuchkov** [comment]
The `feature/v0.4.0` branch will be merged into `develop` by https://github.com/skycoin/skywire/pull/570.
