### ISSUE TITLE
Share app state with visor

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#606]
**Feature description**

Some of the Skywire applications have quite complex logic and state that needs to be displayed to the user. The VPN client for instance needs to perform handshakes and setup local routes etc to run successfully. Simply displaying to the user whether the route used by VPN is up or down is not enough to inform users about current state of the application. We need to think about how to implement either a ad-hoc solution for VPN client specifically or something more generic and versatile.

The VPN client is probably the most relevant case for this feature as we need to report accurately whether the VPN is working and running correctly at any given moment.

**Comment by Senyoret1** [comment]
I just started integrating the VPN client UI with the current API and identified problems with the current implementation. Here are some notes I currently have.

Currently, the only way to get the state of the VPN client app is to call a generic API endpoint with a GET request, which allows to know if the app is running, as well as the remote visor pk and password. This information does not allow to know if the app is connected to the server, if there was an error making the connection, the amount of time the app has been running and information like that. Also, another problem is that the UI has to be constantly querying the backend, which is not really a good way to maintain the UI updated.

I think we will need a websocket endpoint to get events about the VPN client app, so it is possible to know about important events like starting the app, connecting to the server, performing the handshake, finishing the connection, connection errors and things like that.

Also, I thinks these 2 issues should be taken into account: https://github.com/skycoin/skywire/issues/536 and https://github.com/skycoin/skywire/issues/516

**Comment by jdknives** [comment]
Once this is done, we can probably further supress logs on [INFO]. Currently, the transport logs its activities to stdout which is helpful for quickly assessing whether VPN runs successfully atm but wont be needed anymore.

**Comment by jdknives** [comment]
@Senyoret1 we implemented a basic version of this without websockets but with more advanced states. Maybe for now we can just request the state more often in the frontend and later do websockets. You can check out the changes in #630
