### ISSUE TITLE
Problems starting and stopping the VPN apps

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#627]
**Describe the bug**
Making some tests I found 2 different errors when starting and stopping the VPN apps:
- If you configure the VPN client app to connect to a visor which does not have the VPN server app and start it, the VPN client app will only be started for a small moment and then the API will start returning `status: 0`, indicating that the app was stopped. The problem is that when trying to start the VPN client app again the API returns `app already started` and error 500, even if the app is reconfigured to use the pk of a valid server. The problem continues until the visor is restarted.
- If you have both the VPN client and the VPN server apps in the same visor and start the VPN client app for connecting to the VPN server app in the same visor, it will not be possible to stop the VPN client app, unless the visor is restarted. Also, after the error, the manager is not able to make any operation related to the affected visor, because the API starts returning `connection is shut down`.

**Environment information:**

- OS: Linux (Ubuntu 18.04.1)
- Platform: Linux 4.15.0-65-generic x86_64

**Steps to Reproduce**
Steps to reproduce the first problem:
- Start a visor, including the VPN client app.
- Use the Skywire manager to change the server pk configured in the VPN client app to 024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7.
- Press the start button in the Skywire manager, to start the VPN client app.
- Refresh the info in the Skywire manager until the VPN client app appears stopped.
- Press the start button in the Skywire manager, to start the VPN client app again.
- The manager should show `app already started`. If you use the API to check the state of the app, is will return `status: 0`, which should mean that the app is stopped.
- If you refresh the data continually, the app may appear started at some moments, but the behavior is erratic.

Steps to reproduce the second problem:
- Start a visor with the VPN client and VPN server apps.
- Use the Skywire manager to change the server pk configured in the VPN client app to the pk of the visor itself.
- Make sure the VPN server app is running.
- Press the start button in the Skywire manager, to start the VPN client app.
- Wait until the app appears running.
- Press the stop button of the VPN client app and confirm the operation in the modal window.
- After a moment, the modal window should show the `Context deadline exceeded.` error message.
- After the error, the manager will not be able to continue accessing the visor, as the API starts returning `connection is shut down`. The problem is solved restarting the visor.

**Actual behavior**
Both errors force the user to restart the visor to be able to continue using it normally.

**Comment by jdknives** [comment]
Fixed by #635
