### ISSUE TITLE
Make it possible to get more stats from the VPN client app

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#643]
We should have a way for getting the following data from the VPN client app (this is needed for the UI):

- The data transmission stats (upload/download speed and total data uploaded/downloaded)
- The latency.
- For how long the app has been running.

Maybe the changes made in https://github.com/skycoin/skywire/pull/630 can be used as the foundation for this.

**Comment by jdknives** [comment]
@Senyoret1 please check of this solves the first two points: https://github.com/skycoin/skywire/issues/429#issuecomment-735959025

**Comment by Senyoret1** [comment]
I checked https://github.com/skycoin/skywire/issues/429#issuecomment-735959025 and it includes part of the required data. However, there are some things:

- It only has one property for speed and one for total data, so I think there is no way to separate the download and upload speeds, just like there is no way to separate how many data has been sent from how many data has been received.

- I’m not sure about some things, like why does it returns an array of connection properties objects and not just one, if there is chance of the data being resetted in case of connection problems and what the error field is exactly for.

If independent properties for data upload and download are added, the only thing needed would be something for knowing for how many time the app has been running, but that is not super important, so I could simply remove the timer from the UI. If there are problems adding independent properties, I can modify the UI for showing all the data combined, but I think showing the data separated would be better.

CC: @Darkren

**Comment by Darkren** [comment]
@Senyoret1 the application may open more than one connection to the remote visor. And we have an array of connection stats just for that. Other than that, I'll see what can be done
