### ISSUE TITLE
Include more info in the API endpoint for getting the visor list

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#646]
Currently, for populating the visor list, the Skywire manager has make the following API calls:

- `GET api/visors`: for getting the list.
- `GET api/dmsg`: for knowing the dmsg server to which each visor is connected.
-  `GET api/visors/{pk}/health` (one call for each visor): for knowing if the visor has a problem with a service.
- `GET api/about`: for knowing which visor is working as hypervisor.

It would be better if all data could be obtained just by one API call, because having to make several calls make the UI much slower. This could work like the `GET api/visors/{pk}/summary` API endpoint.

Note: this is not prioritary.

**Comment by jdknives** [comment]
Fixed by #666
