### ISSUE TITLE
Hypervisor tests rely on visor field being empty

### ISSUE THREAD

**Issue by i-hate-nicknames** [skycoin/skywire#673]
Currently, hypervisor tests instantiate a hypervisor without a visor:
[hypervisor_test.go](https://github.com/skycoin/skywire/blob/develop/pkg/visor/hypervisor_test.go#L75)

hypervisor code handles this case in some methods:
[hypervisor.go]( https://github.com/skycoin/skywire/blob/develop/pkg/visor/hypervisor.go#L124)

So we end up in a situation when applicaton code exists solely for tests, confusing those who need to maintain it.

I can see the following possible solutions, apart from removing existing tests:

1. Instantiate a real visor from visor config, keep a test visor config somewhere. This will make test initialization heavy, so probably worth moving to integration testing, like so:
https://stackoverflow.com/a/28007631

2. Introduce visor interface and use it in hypervisor instead of concrete Visor type. Then use a mocking library to pass a mock visor in tests. This is a cleaner solution, but will require rewriting hypervisor code to use visor interface, as well as building visor interface itself (decide what should be part of the interface). The mock can be also implemented directly if needed, like it's done with [remote visor connections](https://github.com/skycoin/skywire/blob/develop/pkg/visor/hypervisor.go#L167)  

3. Investigate whether hypervisor actually needs a direct access to visor object. If it's possible to narrow down required functionality to Connection interface (which is used for remote visors now), this is the easiest option to go with.

**Comment by 0pcom** [comment]
closing due to age
