### ISSUE TITLE
Changes to skywire/pkg/app

### ISSUE THREAD

**Issue by devzone777** [skycoin/skywire#678]
I have become aware of some changes to the app package. Now I am trying to confirm how to use the package to do what I need.
Previously I had use app.ClientConfigFromEnv() to get visor_pk, app_server_addr, and app_key

I suspect that this function was eliminated and replaced with appcommon.ProcConfigFromEnv()

Additionally I was using app.NewClient(appName, app.ClientConfigFromEnv())  but now appears to be used with app.NewClient(nil)
app.NewClient should give 2 values but I only get 1, but this might be because of the failure of app.ClientConfigFromEnv()

Can anyone confirm that these changes were made to accommodate the VPN development a few months ago? And if so, how do I properly get ClientConfigFromEnv and pass into app.NewClient()?

**Comment by devzone777** [comment]
Here is an example of the error:
```
b.com/skycoin/dmsg/buildinfo.commit=b467abd45fd744e8b770278920ded3cc2339146f" -o ./apps/baseapp ./cmd/apps/baseapp
# github.com/skycoin/skywire/cmd/apps/baseapp
cmd/apps/baseapp/baseapp.go:36:23: undefined: app.ClientConfigFromEnv
cmd/apps/baseapp/baseapp.go:54:8: undefined: app.NewLogger
cmd/apps/baseapp/baseapp.go:62:9: assignment mismatch: 2 variables but app.NewClient returns 1 values
cmd/apps/baseapp/baseapp.go:62:25: too many arguments in call to app.NewClient
```

**Comment by devzone777** [comment]
Here is a code snippet:
```
const (
        appName = "baseapp"
        netType = appnet.TypeSkynet
        port    = routing.Port(54)
)

var addr = flag.String("addr", ":8005", "address to bind")
var r = netutil.NewRetrier(50*time.Millisecond, 5, 2)
var clientConfig, _ = app.ClientConfigFromEnv()

var (
        baseApp   *app.Client
        clientCh  chan string
        baseConns map[cipher.PubKey]net.Conn
        connsMu   sync.Mutex
        log       = logrus.New() //*logging.MasterLogger
)

type envVars struct {
    VisorPk string `json:"visor_pk"`
    AppServerAddr string `json:"app_server_addr"`
    AppKey string `json:"app_key"`
}


func main() {
        log = app.NewLogger(appName)
        flag.Parse()

        if _, err := buildinfo.Get().WriteTo(log.Writer()); err != nil {
                log.Printf("Failed to output build info: %v", err)
        }


        a, err := app.NewClient(logging.MustGetLogger(fmt.Sprintf("app_%s", appName)), clientConfig)
        if err != nil {
                log.Fatal("Setup failure: ", err)
        }
```

**Comment by devzone777** [comment]
So my question is how to correct this with new functions from /pkg/app and or /pkg/appcommon

**Comment by Darkren** [comment]
Hey there @devzone777 !

Rn it works like this:
`app.NewClient()` accepts only a single argument, indeed. This is `*appevent.Subscriber` which allows to subscribe to some events from our visor. Rn we support 2 kinds of events: `OnTCPDial` and `OnTCPClose` which are fired from the dmsg client iirc. We needed this for the VPN client implementation, so if you don't need this stuff, `nil` may be passed to `app.NewClient()`. This function parses env config inside and panic on error. If you need to pass in your customized config, you may use `app.NewClientFromConfig()`. This one accepts `log logrus.FieldLogger, conf appcommon.ProcConfig, subs *appevent.Subscriber`. The last one may be `nil`, again, if it's not needed. So, with your example, since you get your config from env, it should be done this way:

```
const (
        appName = "baseapp"
        netType = appnet.TypeSkynet
        port    = routing.Port(54)
)

var addr = flag.String("addr", ":8005", "address to bind")
var r = netutil.NewRetrier(50*time.Millisecond, 5, 2)

var (
        baseApp   *app.Client
        clientCh  chan string
        baseConns map[cipher.PubKey]net.Conn
        connsMu   sync.Mutex
        log       = logrus.New() //*logging.MasterLogger
)

type envVars struct {
    VisorPk string `json:"visor_pk"`
    AppServerAddr string `json:"app_server_addr"`
    AppKey string `json:"app_key"`
}


func main() {
        log = app.NewLogger(appName)
        flag.Parse()

        if _, err := buildinfo.Get().WriteTo(log.Writer()); err != nil {
                log.Printf("Failed to output build info: %v", err)
        }


        a := app.NewClient(nil)
```

Please, feel free to ask if you got any questions left

**Comment by devzone777** [comment]
@Darkren Thanks! I will make the changes test
