### ISSUE TITLE
Multiple error during and after VPN client reconnection

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire#705]
**Describe the bug**
When VPN client tries to reconnect to the non-running VPN server there're multiple errors popping in logs. This happens because app doesn't listen for new connections and route itself doesn't get created. So, when client sends hello message, this message gets dropped by remote visor with error. And so do other packets. When VPN server finally gets started all of old routes get created. Eventually they expire and get removed, again, with errors in logs. Overall functionality is not hurt, it works fine, but errors hurt user experience.

**Environment information:**
Independent

**Steps to Reproduce**

1. Run remote visor
2. Run local visor
3. Setup transport between visors
4. Start VPN client, but do not start VPN server

**Comment by 0pcom** [comment]
This is more or less expected behavior.

If a password is set, the vpn server won't show up in the service discovery but will still be accessible. So there is no way to know without attempting connection if the vpn server is running or not, in certain instances.
