### ISSUE TITLE
Allow to retrieve full logs from UI

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#725]
**Feature description**

We need to provide users with an easier way to retrieve the full logs of the visor. Currently we can display application logs but no system logs. 

**Ideas**

If the visor is run as `systemd` service we can simply return the last few thousand lines of logs to the hypervisor. If we are not running it as `systemd` we need to think about a different solution.

**Comment by i-hate-nicknames** [comment]
If the purpose is quick diagnostics for any kind of visor (systemd service or not), the easiest solution looks like this to me.
We simply store the most recent log entries in memory (the number is configurable). There will be no persistence, so the logs of previous runs won't be stored.

Systemd service logs will work as usual, and can be used to get older logs from previous runs. Users that do not use systemd will have to setup logging themselves (rotation, etc).
