### ISSUE TITLE
Fix Windows builds

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#778]
**Describe the bug**

It was reported in https://github.com/skycoin/skywire/pull/772 that the Windows builds are broken. Skywire should build on Windows if following the setup steps [here](https://github.com/skycoin/skywire/blob/master/docs/windows-setup.md). 

We need to investigate the architecture of 

- `syslog`
- `dmsgpty` packages as well. 

They currently do not build but at least for `dmsgpty` we can likely get it to build.

**Comment by 4rchim3d3s** [comment]
Just pulled, checkout to develop, and did `go build -o ./skywire-visor.exe ./cmd/skywire-visor`
 got the following output on Windows:

hope this helps

![image](https://user-images.githubusercontent.com/50741854/120116376-270fec00-c188-11eb-88fd-aee6807cd2a4.png)
