### ISSUE TITLE
Invalid VPN authentication handled incorrectly

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#783]
**Describe the bug**
The vpn client app is not connecting. I ran 2 visors in different virtual machines, using the last changes of the develop branch. When starting the vpn client app of the first visor to connect to the vpn server app of the second visor, the connection is never stablished. A few seconds after starting the app, the client and server apps show this in the console: `Error during close route group: close route group timed out: context deadline exceeded `. Eventually, the visor running the client app panics.

After that, the calls to the `GET /api/visors/{pk}` API endpoint return `Connection failed, reconnecting` in the `detailed_status` property of the vpn client app until the visor is stopped. A problem with this is that, at the same time, the `status` property returns `0`, which the UI interprets as the app being stoped, so the button for stopping the vpn is not shown. Maybe it does not make much sense to report that the app is stopped with the `status` property set to `0` and at the same time report that it is reconnecting with the `detailed_status` property set to `Connection failed, reconnecting`, but if there is a technical reason for that, maybe the UI can be adapted for considering the special case,

**Comment by Senyoret1** [comment]
I checked again and this happens when using an incorrect password for connecting with the vpn server. This means the app works, but the way it is reacting to incorrect passwords is very inadequate. Maybe the client should stop trying after some time.

**Comment by jdknives** [comment]
@Senyoret1 in that case I will rename the ticket. Will fix it.
