### ISSUE TITLE
Data Race

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#798]
**Describe the bug**
Multiple Data Races on startup

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.8.0-55-generic x86_64

**Steps to Reproduce**

1. Go to `develop` branch
2. Run `go build ${BUILD_OPTS} -race -o ./skywire-visor ./cmd/skywire-visor`
3. Run `sudo ./skywire-visor skywire-config.json`

**Actual behavior**
Multiple data races are seen. 
[log.txt](https://github.com/skycoin/skywire/files/6610378/log.txt)

**Expected behavior**
Should start without any data races.

**Additional context**

**Possible implementation**
Hints to fix the bug.

**Comment by jdknives** [comment]
Fixed by #799
