### ISSUE TITLE
Return number of hops in summary

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#804]
**Feature description**
Not sure if possible, but it would be good if `/api/visors/{pk}/summary` and similar API endpoints return how many hops each route has.

**Comment by 0pcom** [comment]
is the setting not globally defined in the visor's config?

**Comment by Senyoret1** [comment]
I was talking about knowing how many hops each route has, from start to finish, but looking at it, it appears to not have much sense now. I will close this issue
