### ISSUE TITLE
Download speed down, from 1Gb to 125Mb

### ISSUE THREAD

**Issue by Secabuster** [skycoin/skywire#823]
@all  I have a 1Gbit/s account in my place, Holland. 
Now i have a problem with the downloadspeed.
I upgraded 2 month ago my visors to 0.4.1 and now is my downloadspeed down to 120 Mbits/s.
It means that my entire WiFi is slow and my home Pc is slow.
I checked it with the mechanic from my provider Ziggo, and the problem are the visors. 
When i have 6 visors online, there is no problem. 
But, when i have all 8 online, i have this problem.
I changed the router with a new one, 1 Gb ports, but no results. 
And i checked the visors one by one, to see if there is not one who is giving the problems. 
All 8 are Ok. 
I am running 0.4.1 and i have Pi Boards 3b+. 
There is no transport on one of my visors. 
What can i do more? 
Can someone give me a answer?

**Comment by jdknives** [comment]
@Secabuster if there are no transport to your visors that means no one is using your visors as network nodes. That entails that the drop in download speed is not related to the network being used for Skywire connections. 

What did the mechanic say exactly? How did he determine that the visors are a problem? How are the visors connected to your home network? 

You can also reach out to us on TG. This seems more like a support issue so contact one of the admins in https://t.me/skywire
