### ISSUE TITLE
Unknow Visor version

### ISSUE THREAD

**Issue by magicstone1412** [skycoin/skywire#832]
**Describe the bug**
I have updated skywire to version 0.4.2 using Docker container but it shows `Visor version: unknown` in `VISOR INFO`

**Environment information:**

- OS: Linux, Windows, Mac OS X
- Platform: arm64 (aarch64)

**Steps to Reproduce**

1. Clone skywire repo to local

```
git clone https://github.com/skycoin/skywire.git
```
2. Remove `GOARCH=amd64 \` in '~/skywire/docker/images/visor/Dockerfile'
3. Run 'docker build -t skywire:v0.4.2 -f ./docker/images/visor/Dockerfile .'
4. Generate config `docker run --rm -v ~/.config/skywire:/opt/skywire skywire:v0.4.2 skywire-cli visor gen-config --is-hypervisor`
5. Run container

```
docker run --rm \
    --name=visor \
    --net=host \
    -v ~/.config/skywire:/opt/skywire \
 skywire:v0.4.2 skywire-visor
``` 

6. Open hypervisor manager page `<IP>:8000`

**Actual behavior**

Please see the below image
![2021-07-02 22_08_12-Window](https://user-images.githubusercontent.com/9553811/124294590-11745480-db82-11eb-85c3-99b2ea5f3511.jpg)

**Expected behavior**
Should see version number in the line `Visor version: unknown`

**Additional context**
No more.

**Comment by jdknives** [comment]
@magicstone1412 fix was merged. Will close this for now. Thanks for reporting.
