### ISSUE TITLE
Backport master fixes to Milestone2 

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#84]
**Describe the bug**
Some fixes have been applied to `master` but not to `milestone2`. Notably, these include

- [x] fixes to the hypervisor made by Evan
- [x] changing app config values from slice to map
- [x] listening on stcp by default
- [x] transport deregistration logic changes
- [x] remove `therealssh`

**Comment by nkryuchkov** [comment]
> remove `therealssh`

https://github.com/SkycoinProject/skywire-mainnet/issues/55

**Comment by jdknives** [comment]
Completed.
