### ISSUE TITLE
Improve naming consistency and documentation

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#85]
From Discord: 

We are currently 

- using messaging in many instances instead of dmsg. 
- using node instead of visor (notably in the skywire-cli command and many more instances in the codebase)
- using therealproxy where we should probably switch to a more straightforward name of skyproxy
- talking in documentation about docker setups that do not exist anymore

**Comment by nkryuchkov** [comment]
> using messaging in many instances instead of dmsg.

https://github.com/SkycoinPro/skywire-services/issues/26

> using node instead of visor (notably in the skywire-cli command and many more instances in the codebase)

https://github.com/SkycoinProject/skywire-mainnet/issues/96

> using therealproxy where we should probably switch to a more straightforward name of skyproxy

https://github.com/SkycoinProject/skywire-mainnet/issues/97

> talking in documentation about docker setups that do not exist anymore

https://github.com/SkycoinPro/skywire-services/issues/43
