### ISSUE TITLE
Improve app configurability from Hypervisor

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#86]
**Feature description**

Currently, we can only set the autostart parameter for applications on a visor from the hypervisor and start/stop applications. `skyproxy` as well as `dmsgpty` require more control however. 

Users should be able to 

-  enable/disable authentication and change auth passcode for `skyproxy`
-  set and manage the whitelist for `dmsgpty`

**Comment by nkryuchkov** [comment]
Setting and managing the whitelist for `dmsgpty` is put on hold for now because `dmsgpty` was moved from visor apps.
