### ISSUE TITLE
Unstable test case

### ISSUE THREAD

**Issue by mrpalide** [skycoin/skywire#865]
**Describe the bug**
The `Uptime` test case on [`/pkg/visor/rpc_test.go`](../tree/develop/pkg/visor/rpc_test.go#L98) has unstable behavior on AppVeyor MacOS image, sometimes passed and sometimes failed.
These are my last three tests, the [oldest](https://ci.appveyor.com/project/mrpalide/skywire/builds/40516202) PASSED, [next one](https://ci.appveyor.com/project/mrpalide/skywire/builds/40516805) FAILED and the [latest](https://ci.appveyor.com/project/mrpalide/skywire/builds/40516806) PASSED again!
This problem just happened in MacOS image and everything is OK on Linux image.

**Comment by alexadhy** [comment]
The cause is probably slight delay while testing for uptime, probably we should change the test case itself, rather than matching it against `string` , we could compare uptime against minimum expected uptime (say 1 second) for example.

**Comment by mrpalide** [comment]
Fixed in #854
