### ISSUE TITLE
Two dataraces on visor shutdown

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#890]
**Describe the bug**
On closing the visor with `Ctrl+C` 2 data races are seen.

**Environment information:**

- OS: Linux
- Platform: Linux 5.11.0-34-generic x86_64

**Steps to Reproduce**

1. Run `go build -race -o ./skywire-visor ./cmd/skywire-visor`
2. Run `./skywire-visor skywire-config.json`
3. Press `Ctrl+C`

**Actual behavior**
On closing the visor with `Ctrl+C` 2 data races are seen.
[datarace.log](https://github.com/skycoin/skywire/files/7216561/datarace.log)

**Expected behavior**
Visor shutdown without any error.

**Comment by alexadhy** [comment]
Can be reproduced in macOS as well
