### ISSUE TITLE
Datarace while stopping vpn-server app

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#896]
**Describe the bug**
A datarace is seen when a `vpn-server` app is stopped.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.11.0-36-generic x86_64

**Steps to Reproduce**

1. Run
```shell
$ go build -race -o ./apps/vpn-server ./cmd/apps/vpn-server
$ go build -race -o ./skywire-visor ./cmd/skywire-visor
```
2. Run './skywire-visor skywire-config.json'
3. Start the `vpn-server` from hypervisor UI and then stop it

**Actual behavior**
[datarace.log](https://github.com/skycoin/skywire/files/7236284/datarace.log)

**Expected behavior**
Stop `vpn-server` without datarace.

**Comment by alexadhy** [comment]
#897 seems to have fixed this, can't reproduce it with latest develop.

**Comment by ersonp** [comment]
Can't replicate the error anymore after #897 on Linux either. Closing this.
