### ISSUE TITLE
Visors cannot connect to hypervisor

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#91]
**Describe the bug**
When running the integration environment, connections between visors and hypervisor stuck in dmsg code.

**Environment information:**
Independent.

**Steps to Reproduce**
Run the generic integration environment.

**Actual behavior**
Visors cannot connect to hypervisor.

**Expected behavior**
Visors connect to hypervisor.

**Comment by Darkren** [comment]
We need to adjust other env configs too

**Comment by nkryuchkov** [comment]
Other env configs don't seem to have hypervisors enabled.
