### ISSUE TITLE
[M2] Socket files are not removed on visor shutdown

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire#93]
**Describe the bug**
Socket files (app serve and dmsgpty) are not removed on visor shutdown. This way if we restart visor, it won't run because of `address already in use`

**Environment information:**
Independent

**Steps to Reproduce**

1. Run skywire visor
2. Shutdown visor
3. Run it again

**Actual behavior**
Visor fails to run because of `address already in use`

**Expected behavior**
Visor runs

**Possible implementation**
Remove socket files on visor shutdown

**Comment by jdknives** [comment]
Closed by #113
