### ISSUE TITLE
VPN UI not opening issue

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#932]
**Describe the bug**
The vpn UI does not open on local hypervisor but opens on remote visor if `enable_auth` is set to be `true` in the config. 
The vpn UI opens on local hypervisor but  does not open on remote visor if `enable_auth` is set to be `false` in the config. 

**Environment information:**

- OS: Linux
- Platform: Linux 5.11.0-37-generic x86_64

**Steps to Reproduce**
1. Update configs of `integration/intermediary-visorB.json`, `integration/generic/visorA.json`, `integration/generic/visorA.json` with 
```
			{
				"name": "vpn-client",
				"auto_start": false,
				"port": 43
			}
```
inside `"apps"`
2. Start `integration env`
3. Set `enable_auth` of hypervisor config to `false`
4. Go to `vpn UI` of hypervisor
5. Go to `vpn UI` of visor A
6. Do the same for `enable_auth`  `true`0

**Actual behavior**
`http://localhost:8000/#/vpn/unavailable?problem=pkChange` sometimes we are redirected here and sometimes the page becomes unresponsive.

**Comment by Senyoret1** [comment]
I performed multiple tests and was unable to reproduce the issue. I made some changes recently to the authentication detection in https://github.com/skycoin/skywire/pull/792 , which was merged just hours ago. Could you please make sure you are using the last changes added to the develop branch from that PR?

**Comment by ersonp** [comment]
Okay, will test it out and let you know.
