### ISSUE TITLE
`pty` not working in v0.5.0 and v0.5.1

### ISSUE THREAD

**Issue by asxtree** [skycoin/skywire#966]
**Describe the bug**
The Full terminal is not working on v0.5.0 and v0.5.1 when using the button from UI or by manually openning it.

**Environment information:**

- Skywire Manager UI
- Skybian and Skyraspbian images used
- Edge or Chrome browsers used with block popup disabled

**Steps to Reproduce**

1. Select Full terminal from the visor UI.
2. A new page opens showing `[dmsgpty-ui] Status: Dialing... `                                                                    
3. After a few seconds the messages `[dmsgpty-ui] Error: i/o deadline reached` `[dmsgpty-ui] Status: Stopped!` gets displayed

Alternative method

1. Open a web page and navigate to http://hypervisorIP:8000/pty/{pk}
2. The message `[dmsgpty-ui] Status: Dialing... ` appears then the messages `[dmsgpty-ui] Error: i/o deadline reached` `[dmsgpty-ui] Status: Stopped!` gets displayed

**Actual behavior**
The messages `[dmsgpty-ui] Error: i/o deadline reached` `[dmsgpty-ui] Status: Stopped!` gets displayed in the web page
![pty-error](https://user-images.githubusercontent.com/34941232/138650134-59a9fcea-8533-4382-bd07-92fca67646bd.png)

On the board ssh this error gets displayed:

`Oct 25 07:22:39 raspberrypi skywire-visor[11821]: [2021-10-25T07:22:39+01:00] INFO [dmsgC]: Failed to accept stream. error="dmsg error 306 - request has no associated listener" session=03d5b55d1133b26485c664cf8b95cff6746d1e321c34e48c9fed293eff0d6d49e5`

**Expected behavior**
Terminal works.

**Additional context**
Skywire config file for further test is attached and renamed to skywire-config.json.txt.
[skywire-config.json.txt](https://github.com/skycoin/skywire/files/7407991/skywire-config.json.txt)

**Comment by alexadhy** [comment]
Should be fixed now.
