### ISSUE TITLE
`skywire-cli config gen` flag to preserve or retain configured hypervisors

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#982]
**Feature description**

currently we have the `-r` flag for retaining the public / private keys in a config file when regenerating it. However there is no similar method for retaining the hypervisors which may be set in the config file.

I propose a new flag; `-R` to retain any remote hypervisor configutration.

```
skywire-cli config gen -R -o /path/to/skywire-config.json
```
* this flag should be mutually exclusive with the -i flag (or else we need documentation on using a local and remote hypervisor simultaneously)
* this flag __may__ combine the function of the `-r` flag for brevity as they are likely to be used together almost exclusively

**Is your feature request related to a problem? Please describe.**

In the package-based skywire installation, the config generation process is used more extensively in scripts which generate configuration files that work with the available systemd services for two modes of operation (with hypervisor or visor-only / remote hypervisor)

Unfortunately, when users install the skywire-bin package I maintain, they must reconfigure the visors to their hypervisor as a consequence of lacking a way to retain the hypervisor configuration.

**Comment by 0pcom** [comment]
I am not opposed to the behavior I described being the default for the `-r` flag and over-rideable by the `-i` and `--hypervisor-pks` flags, however, in the latter instance __it would be nice__ to be able to add a hypervisor to the list of hypervisors which was already configured without deleting what is there.

It would also be valuable if skywire-cli could tell you what hypervisor public keys are set in a config file, similar to `skywire-cli visor pk`

perhaps `skywire-cli visor hvpk` or hvpks

but it should really be able to parse the config file for this (and the existing `visor pk` command) optionally, as an alternative to asking the running visor..

**Comment by jdknives** [comment]
Fixed by the above commit in #981
